### ISSUE TITLE
Some query fail on Huawei devices despite same sqlite same version as other brands

### ISSUE THREAD

**Issue by EArminjon** [tekartik/sqflite#1023]
Hi,

I notice that, on Huawei the following request fail : 

```sql
SELECT *
FROM sch_index
WHERE usually_in_stock = 'true'
  AND (sch_index MATCH 'level_one:^010705\$' OR
       sch_index MATCH 'level_two:^010705\$' OR
       sch_index MATCH 'level_three:^010705\$')
```

Got the error on Huawei P40 pro (tested on the Huawei Cloud debugging website, my clients got the same errors on P20 pro)

```
DatabaseException(unable to use function MATCH in the requested context (Sqlite code 1 SQLITE_ERROR), (OS error - 2:No such file or directory)) sql '      SELECT *
2023-06-15 11:09:28 24156-10636/? I/flutter: FROM sch_index
2023-06-15 11:09:28 24156-10636/? I/flutter: WHERE enabled = 'true'
2023-06-15 11:09:28 24156-10636/? I/flutter:   AND (sch_index MATCH 'level_one:^010705$' OR
2023-06-15 11:09:28 24156-10636/? I/flutter:        sch_index MATCH 'level_two:^010705$' OR
2023-06-15 11:09:28 24156-10636/? I/flutter:        sch_index MATCH 'level_three:^010705$')
2023-06-15 11:09:28 24156-10636/? I/flutter: 
2023-06-15 11:09:28 24156-10636/? I/flutter: LIMIT 100 OFFSET 0
2023-06-15 11:09:28 24156-10636/? I/flutter: ' args []
2023-06-15 11:09:28 24156-10636/? I/flutter: #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
2023-06-15 11:09:28 24156-10636/? I/flutter: <asynchronous suspension>
2023-06-15 11:09:28 24156-10636/? I/flutter: #1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:559:30)
2023-06-15 11:09:28 24156-10636/? I/flutter: <asynchronous suspension>
2023-06-15 11:09:28 24156-10636/? I/flutter: #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
2023-06-15 11:09:28 24156-10636/? I/flutter: <asynchronous suspension>
2023-06-15 11:09:28 24156-10636/? I/flutter: #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:490:14)
2023-06-15 11:09:28 24156-10636/? I/flutter: <asynchronous suspension>
2023-06-15 11:09:28 24156-10636/? I/flutter: #4      
```

Smell like, for a weird reason, we cannot use multiple MATCH keyword on Huawei... Maybe something take care only of the first one or remove the others, I didn't understand why on other devices that works.

Here is how I create virtual table : 

```sql
CREATE TABLE IF NOT EXISTS `game` (
  id TEXT NOT NULL,
  level_one TEXT,
  level_one TEXT,
  level_three TEXT,
  enabled TEXT,
  url TEXT
);

CREATE VIRTUAL TABLE IF NOT EXISTS sch_index USING fts4(
  content='game',
  tokenize=unicode61, id, level_one, level_two, level_three, enabled, url},
  notindexed=enabled,
  notindexed=url
);

... 
// I didn't provide trigger to auto insert in the FTS table
```

**Comment by EArminjon** [comment]
Feel like the Huawei sqlite API is not the exactly same as other brands... Weird, despite the same sqlite lite version we got difference that could mean they add extra code / implementation on it, crazy or possible ?

**Comment by alextekartik** [comment]
> despite having the same sqlite lite version

Having the same sqflite version does mean having the same SQLite version unfortunately.
sqflite uses whatever SQLite version is installed on the device so it might differ between devices.
See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/version.md

One safe solution would be to use sqflite_common_ffi along with sqlite_flutter_libs to use a consistent SQLite version.

**Comment by EArminjon** [comment]
> One safe solution would be to use sqflite_common_ffi along with sqlite_flutter_libs to use a consistent SQLite version.

Does that mean i need to remove sqflite from my dependencies to only use sqflite_common_ffi ?

**Comment by alextekartik** [comment]
Yes you can remove it if you only use sqflite_common_ffi.

**Comment by EArminjon** [comment]
> > despite having the same sqlite lite version
> 
> Having the same sqflite version does mean having the same SQLite version unfortunately. sqflite uses whatever SQLite version is installed on the device so it might differ between devices. See https://github.com/tekartik/sqflite/blob/master/sqflite/doc/version.md

I'm not sure you get what I said : My Pixel and Huawei got the same sqlite version (not sqflite) and react in 2 different way.
That's what I've trouble to understand : how 2 versions of sqlite can product 2 different outputs... 

I well understand that sqflite version isn't linked to the device sqlite version.

**Comment by alextekartik** [comment]
What are the SQLite versions on both devices ?
```
print((await db.rawQuery('SELECT sqlite_version()')).first.values.first);
```

**Comment by EArminjon** [comment]
3.22.0

**Comment by alextekartik** [comment]
puzzling indeed. I'm not sure whether FTS extensions is consistent on all devices and don't know how to check it (I have never used it).

**Comment by Mike278** [comment]
You can check what compile options were used by running the query `pragma compile_options`.

**Comment by dharmaturtle** [comment]
Are you _sure_ it works on other devices? According to [this](https://stackoverflow.com/questions/31891456/sqlite-fts-using-or-between-match-operators) and [this](https://sqlite-users.sqlite.narkive.com/LFoT02Lj/sqlite-error-unable-to-use-function-match-in-the-requested-context), `OR` doesn't work with `match` in FTS3, FTS4, or FTS5.
