### ISSUE TITLE
Exception when running setup for sqflite_common_ffi_web

### ISSUE THREAD

**Issue by Amir-P** [tekartik/sqflite#1032]
Running `dart run sqflite_common_ffi_web:setup` with or without `--force` results in a `ShellException`.

Dependencies:

```
sqflite: 2.2.5
sqflite_common: 2.4.3
sqflite_common_ffi: 2.2.3
sqflite_common_ffi_web: 0.3.4
```

Logs:

```
Building sqflite_common_ffi_web shared worker
.../.dart_tool/sqflite_common_ffi_web/setup/3.0.7+9
$ dart pub get
Resolving dependencies...
+ _fe_analyzer_shared 62.0.0
+ analyzer 6.0.0
+ archive 3.3.7
+ args 2.4.2
+ async 2.11.0
+ bazel_worker 1.0.3
+ boolean_selector 2.1.1
+ build 2.4.1
+ build_config 1.1.1
+ build_daemon 4.0.0
+ build_modules 5.0.3
+ build_resolvers 2.2.1
+ build_runner 2.4.6
+ build_runner_core 7.2.10
+ build_web_compilers 4.0.4
+ built_collection 5.1.1
+ built_value 8.6.1
+ charcode 1.3.1
+ checked_yaml 2.0.3
+ code_builder 4.5.0
+ collection 1.17.2
+ convert 3.1.1
+ coverage 1.6.3
+ crypto 3.0.3
+ dart_internal 0.2.8
+ dart_style 2.3.2
+ dev_test 0.16.1+4
+ ffi 2.0.2
+ file 7.0.0
+ fixnum 1.1.0
+ frontend_server_client 3.2.0
+ glob 2.1.2
+ graphs 2.3.1
+ http 1.1.0
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.4
+ js 0.6.7
+ json_annotation 4.8.1
+ lints 2.1.1
+ logging 1.2.0
+ matcher 0.12.16
+ meta 1.9.1
+ mime 1.0.4
+ node_preamble 2.0.2
+ package_config 2.1.0
+ path 1.8.3
+ pointycastle 3.7.3
+ pool 1.5.1
+ process_run 0.13.0
+ protobuf 3.0.0
+ pub_semver 2.1.4
+ pubspec_parse 1.2.3
+ scratch_space 1.0.2
+ shelf 1.4.1
+ shelf_packages_handler 3.0.2
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.12
+ source_span 1.10.0
+ sqflite_common 2.4.5+1
+ sqflite_common_ffi 2.2.5
+ sqlite3 2.0.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ stream_transform 2.1.0
+ string_scanner 1.2.0
+ synchronized 3.1.0
+ term_glyph 1.2.1
+ test 1.24.4
+ test_api 0.6.1
+ test_core 0.5.4
+ timing 1.0.1
+ typed_data 1.3.2
+ vm_service 11.7.2
+ watcher 1.1.0
+ web_socket_channel 2.4.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.2
Changed 80 dependencies!
$ dart pub global run webdev build -o web:build
[INFO] Building new asset graph completed, took 1.2s
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] build_web_compilers:entrypoint on web/sqflite_sw.dart: Running `dart compile js` with --minify --libraries-spec=.../flutter/bin/cache/dart-sdk/lib/libraries.json --packages=org-dartlang-app:///.dart_tool/package_config.json --multi-root-scheme=org-dartlang-app --multi-root=/private/var/folders/dr/j1rnzzkx1kq9fw7sdfnxrxqr0000gn/T/scratch_spaceCWKynp/ -oweb/sqflite_sw.dart.js org-dartlang-app:///web/sqflite_sw.dart
[SEVERE] build_web_compilers:entrypoint on web/sqflite_sw.dart: ExitCode:1
StdOut:
Info: Compiling with sound null safety.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/sqflite_ffi_impl_web.dart@764+10:
Error: Type 'FileSystem' not found.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/sqflite_ffi_impl_web.dart@899+10:
Error: Type 'FileSystem' not found.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/sqflite_ffi_impl_web.dart@764+10:
Error: 'FileSystem' isn't a type.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/web/load_sqlite_web.dart@850+1:
Error: The argument type 'IndexedDbFileSystem' can't be assigned to the parameter type 'FileSystem?'.
 - 'IndexedDbFileSystem' is from 'package:sqlite3/src/wasm/vfs/indexed_db.dart' ('org-dartlang-app:///packages/sqlite3/src/wasm/vfs/indexed_db.dart').
 - 'FileSystem' is from 'dart:html'.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/web/load_sqlite_web.dart@1975+17:
Error: Method not found: 'SqliteEnvironment'.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/web/load_sqlite_web.dart@1963+1:
Error: Too many positional arguments: 1 allowed, but 2 found.
org-dartlang-app:///packages/sqlite3/src/wasm/sqlite3.dart@1126+4:
Info: Found this candidate, but the arguments don't match.
Error: Compilation failed.

StdErr:

[INFO] Running build completed, took 5.0s
[INFO] Caching finalized dependency graph completed, took 164ms
[SEVERE] Failed after 5.2s
[SEVERE] FailureType: 1
Unhandled exception:
ShellException(dart pub global run webdev build -o web:build, exitCode 1, workingDirectory: .../.dart_tool/sqflite_common_ffi_web/setup/3.0.7+9)
```

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4.1 22F82 darwin-arm64, locale
    en-US)
    • Flutter version 3.10.0 on channel stable at .../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (10 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at .../SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = .../SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by Amir-P** [comment]
Changing the `sqflite` and `sqflite_common_ffi` to the latest version fixed the problem for me.

**Comment by Amir-P** [comment]
Hi @alextekartik , I'm having this issue again running `dart run sqflite_common_ffi_web:setup` but with a different exception. Any idea what might have caused the issue?

**Logs:**

```console
Building sqflite_common_ffi_web shared worker
/.dart_tool/sqflite_common_ffi_web/setup/3.0.12+14
$ dart pub get
Resolving dependencies...
  built_value 8.7.0 (8.8.0 available)
  dart_style 2.3.3 (2.3.4 available)
+ dev_build 0.16.3+1
  http 1.1.0 (1.1.2 available)
  process_run 0.13.2 (0.13.3 available)
These packages are no longer being depended on:
- dev_test 0.16.3
Changed 2 dependencies!
$ dart pub global run webdev build -o web:build
[INFO] Building new asset graph completed, took 892ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Unhandled exception:
Instance of 'MissingPortFile'
#0      _existingPort (package:build_daemon/client.dart:24:37)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:180:9)
<asynchronous suspension>
#2      BuildCommand.run (package:webdev/src/command/build_command.dart:66:20)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:12)
<asynchronous suspension>
#5      run (package:webdev/src/webdev_command_runner.dart:19:46)
<asynchronous suspension>
#6      main (file:///.pub-cache/hosted/pub.dev/webdev-3.0.6/bin/webdev.dart:17:16)
<asynchronous suspension>
Unhandled exception:
ShellException(dart pub global run webdev build -o web:build, exitCode 255, workingDirectory: /.dart_tool/sqflite_common_ffi_web/setup/3.0.12+14)
```

**Dependencies:**

```yaml
  sqflite_common_ffi_web: ^0.4.1
  sqflite_common_ffi: ^2.3.0+4
  sqflite: ^2.3.0
  sqlite3: ^2.1.0
```

`flutter doctor -v`:

```console
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.1.1 23B81 darwin-arm64, locale
    en-US)
    • Flutter version 3.13.7 on channel stable at /flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (7 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /SDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/amirpanahandeh/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.1 23B81
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by alextekartik** [comment]
There seems to be an issue with the global `webdev` installed. Can you try to upgrade with the latest version (sqflite_common_ffi_web 0.4.2, it uses a local webdev dependency instead) and run:
```
dart run sqflite_common_ffi_web:setup --force
```

**Comment by Amir-P** [comment]
Thanks! Upgrading to `0.4.2` solves the issue.

**Comment by mgdonato23** [comment]
I had a similar error when running the command dart run sqflite_common_ffi_web:setup

[SEVERE] build_web_compilers:entrypoint on web/sqflite_sw.dart: ExitCode:1
StdOut:
org-dartlang-app:///packages/sqflite_common_ffi_web/src/web/load_sqlite_web.dart@2157+1:
Error: The argument type 'String' can't be assigned to the parameter type 'JSAny'.
org-dartlang-app:///packages/sqflite_common_ffi_web/src/web/load_sqlite_web.dart@2451+1:
Error: The argument type 'String' can't be assigned to the parameter type 'JSAny'.
Error: Compilation failed.

StdErr:

[INFO] Running build completed, took 30.9s
[INFO] Caching finalized dependency graph completed, took 425ms
[SEVERE] Failed after 31.4s
[SEVERE] FailureType: 1
Unhandled exception:
ShellException(dart run webdev:webdev build -o web:build, exitCode 1, workingDirectory: C:\TGT\Target Tab Catalogo\TargetTabCatalogoAPP\Tab\.dart_tool\sqflite_common_ffi_web\setup\5.0.0+40)

**Comment by alextekartik** [comment]
Are you using thé latest version (required for web 1.0.0)

**Comment by mgdonato23** [comment]
I can't because of other packages

Because sqflite_common_ffi_web >=0.4.3+2 depends on web >=1.0.0 <3.0.0 and package_info_plus >=6.0.0 depends on web >=0.5.0 <=0.6.0, sqflite_common_ffi_web >=0.4.3+2 is incompatible with package_info_plus >=6.0.0.
And because every version of target_essentials from path depends on package_info_plus ^8.0.0, sqflite_common_ffi_web >=0.4.3+2 is incompatible with target_essentials from path.
So, because tab depends on both target_essentials from path and sqflite_common_ffi_web ^0.4.4, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on sqflite_common_ffi_web: flutter pub add sqflite_common_ffi_web:'^0.4.3+1'

**Comment by alextekartik** [comment]
Ok I see, there is indeed an unfortunate breaking change in web 1.0.0 that prevents compatibility for the setup tool.

I can see 2 workarounds until your project supports web 1.0.0

### Solution 1: Temp overrides

Temporarily overrides the dependency - just to setup the workers.

```
# Temporarily add the overrides
flutter pub add 'override:sqflite_common_ffi_web:>=0.4.4' override:web:^1.0.0
# Setup the worker
flutter pub run sqflite_common_ffi_web:setup --force
# Remove the overrides
flutter pub remove override:sqflite_common_ffi_web override:web
```

### Solution 2: Create the worker in another project

The workaround here is to run the setup in another project and copy the generated `web/sqlite3.wasm`  and `web/sqflite_sw.js`

```
dart create -t web tmpsqfliteweb --force
cd tmpsqfliteweb
dart pub add sqflite_common_ffi_web
dart pub run sqflite_common_ffi_web:setup
```
