### ISSUE TITLE
Not an error as an error

### ISSUE THREAD

**Issue by JCKodel** [tekartik/sqflite#1105]
```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(Error Domain=SqfliteDarwinDatabase Code=0 "not an error" UserInfo={NSLocalizedDescription=not an error}) sql 'PRAGMA quick_check;' args []
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#2      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:517:14)
<asynchronous suspension>
```

If is not an error, why throw an exception? >.<

This happens with `PRAGMA quick_check;`, `PRAGMA integrity_check;` and `VACUUM;` on iOS at least.

So, if it is `not an error`, don't throw an error!

<img width="1398" alt="image" src="https://github.com/tekartik/sqflite/assets/379339/3ce42e79-96d9-4ac1-a095-0a94ac28d0b3">

**Comment by JCKodel** [comment]
> Can you try using rawQuery

Yes, it worked with `rawQuery`.
