### ISSUE TITLE
pod spec lint fails for sqflite/sqflite_darwin/darwin/sqflite_darwin.podspec

### ISSUE THREAD

**Issue by iulian0512** [tekartik/sqflite#1139]
Hello i wanted to let you know that pod spec lint fails for this podspec 

here is a run of podspec lint --verbose 

```

  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
 -> sqflite_darwin
  sqflite_darwin (0.0.4) - Analyzing on iOS 12.0 platform.
  - Generating Info.plist file at `../../../../../../var/folders/v2/rxxl_sqx5rg_9dwwmxcglydr0000gn/T/CocoaPods-Lint-20241104-18692-uq4o8c-sqflite_darwin/App/App-Info.plist`
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `sqflite_darwin` from `/Users/ics/github/sqflite/sqflite_darwin/darwin/sqflite_darwin.podspec`

Resolving dependencies of 
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_c_0_4.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/3.13.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.16.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.16.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.13.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.13.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.10.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.5/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.2.2/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/2.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.22.4/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.17.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.12.1303/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/1.9.102/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/3.13.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/3.0.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/2.10.2/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/2.5/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/2.0.2/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/2.0.1/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/2.0.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.22.4/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.20.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.17.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.12.1309/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.12.1307/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.12.1303/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.9.102/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.3.300/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.3.200/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.3.1/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.2.1/Flutter.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/c/0/4/Flutter/1.0.0/Flutter.podspec.json exists! Returning local because checking is only performed in repo update

Comparing resolved specification to the sandbox manifest
  A Flutter
  A sqflite_darwin

Downloading dependencies

-> Installing Flutter (3.13.0)
  > Copying Flutter from `/Users/ics/Library/Caches/CocoaPods/Pods/Release/Flutter/3.13.0-8ff16` to `../../../../../../private/var/folders/v2/rxxl_sqx5rg_9dwwmxcglydr0000gn/T/CocoaPods-Lint-20241104-18692-uq4o8c-sqflite_darwin/Pods/Flutter`

-> Installing sqflite_darwin (0.0.4)
 -> sqflite_darwin (0.0.4)
    - WARN  | description: The description is shorter than the summary.
    - WARN  | keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, svn`.
    - NOTE  | url: The URL (https://github.com/tekartik/sqflite/sqflite_darwin) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error (Unsupported download strategy `{:https=>"https://github.com/tekartik/sqflite/tree/master/sqflite_darwin"}`.
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader.rb:92:in `class_for_options'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader.rb:75:in `preprocess_options'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/downloader.rb:132:in `preprocess_request'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/downloader.rb:37:in `download'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:535:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:257:in `download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:582:in `block in download_pod'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:582:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:582:in `download_pod'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:404:in `block in perform_extensive_analysis'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:398:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:398:in `perform_extensive_analysis'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/validator.rb:129:in `validate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/spec/lint.rb:90:in `block in run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/spec/lint.rb:71:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/spec/lint.rb:71:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 2 warnings.

/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/spec/lint.rb:107:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'

```

**Comment by alextekartik** [comment]
Thank you for the report. I fixed some issue but some remains. I tried on path_provider_foundation (which I use as base information). Not sure what to do next...
