### ISSUE TITLE
[Only iOS] error DatabaseException(Error Domain=SqfliteDarwinDatabase Code=1 "near "order": syntax error" UserInfo={NSLocalizedDescription=near "order": syntax error}) sql '

### ISSUE THREAD

**Issue by devnta** [tekartik/sqflite#1147]
This issue  only happens on iOS (Simulator version 18.0), Android no problem.
My code:
```
Future<Database> _createDatabase() async {
    return openDatabase(
      // Set the path to the database. Note: Using the `join` function from the
      // `path` package is best practice to ensure the path is correctly
      // constructed for each platform.
      join(await getDatabasesPath(), 'myTestingDb.db'),
      onCreate: (db, version) async {
        // Run the CREATE TABLE statement on the database.
        // TODO: Create multiple tables here.
        await db.execute(
          '''
          CREATE TABLE myTableTesting (
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            title TEXT,
            description TEXT,
            deadline TEXT,
            category TEXT,
            order INTEGER,
            isCompleted INTEGER,
            isDefault INTEGER
          )
          ''',
        );
        return;
      },
      version: 1,
    );
  }
```

Get an error:
```
flutter: error DatabaseException(Error Domain=SqfliteDarwinDatabase Code=1 "near "order": syntax error" UserInfo={NSLocalizedDescription=near "order": syntax error}) sql '          CREATE TABLE myTableTesting (
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            title TEXT,
            description TEXT,
            deadline TEXT,
            category TEXT,
            order INTEGER,
            isCompleted INTEGER,
            isDefault INTEGER
          )
          ' args [] during open, closing...
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: DatabaseException(Error Domain=SqfliteDarwinDatabase Code=1 "near "order": syntax error" UserInfo={NSLocalizedDescription=near "order": syntax error}) sql '          CREATE TABLE myTableTesting (
            id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            title TEXT,
            description TEXT,
            deadline TEXT,
            category TEXT,
            order INTEGER,
            isCompleted INTEGER,
            isDefault INTEGER
          )
          ' args []
#0      wrapDatabaseException (package:sqflite_platform_interface/src/platform_exception.dart:12:7)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:485:16)
<asynchronous suspension>
#2      LocalStorageService._createDatabase.<anonymous closure> (package:my_app/service/local_storage_service.dart:26:9)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.doOpen.<anonymous closure> (p<…>
```

Flutter information:
```
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (4 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
```
Version sqflite:
```
sqflite: ^2.4.1
```

**Comment by devnta** [comment]
But, It’s strange that this only occurs on iOS.
