### ISSUE TITLE
could not open db on real IOS device

### ISSUE THREAD

**Issue by guuguo** [tekartik/sqflite#128]
### My code is running well on Android and iOS simulators.but not on real IOS device.

> error bellow
```
error opening!: 14
Could not create database queue for path /var/mobile/Containers/Data/Application/0D779FBA-6DD7-47D8-B23A-7E1AE744BFA7/Documentsdemo.db
Could not open db.
```

```
Dart Error: Unhandled exception:
DatabaseException(open_failed /var/mobile/Containers/Data/Application/0D779FBA-6DD7-47D8-B23A-7E1AE744BFA7/Documentsdemo.db)
#0      wrapDatabaseException (package:sqflite/src/exception.dart:126:7)
<asynchronous suspension>
#1      SqfliteDatabase.openDatabase (package:sqflite/src/database.dart:489:18)
<asynchronous suspension>
#2      SqfliteDatabase.doOpen (package:sqflite/src/database.dart:521:28)
<asynchronous suspension>
#3      SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:169:26)
<asynchronous suspension>
#4      Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
#5      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
#6      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
#7      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
#8      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:166:25)
<asynchronous suspension>
#9      SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:179:41)
```
## Below is the code for my DB.
```
class DB {
  static Database db;

  static Future open() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = documentsDirectory.path + "demo.db";

    db = await openDatabase(path, version: 1,
        onCreate: (Database db, int version) async {
          await db.execute(ComicRead.createSQL);
          await db.execute(ComicStore.createSQL);
        }, onUpgrade: (Database db, int version, int newVer) async {
          if (newVer == 2)
            await db.execute(ComicStore.createSQL);
        }, onDowngrade: (Database db, int version, int newVer) {
          deleteDatabase(path);
        });
  }

  static Future close() async => db.close();

}
```
I do not know why

**Comment by alextekartik** [comment]
At first I would say (based on assumptions here: <https://github.com/tekartik/sqflite/blob/master/doc/opening_db.md#solving-exceptions>) that you should make sure the parent directory exists. However this (creating the directory if necessary) should be done automatically in the latest sqflite version. Which version of sqflite are you using?
