### ISSUE TITLE
Unrecognized Token Error

### ISSUE THREAD

**Issue by softronaut** [tekartik/sqflite#196]
I'm sending String but getting unrecognized token error as you see. I'm not expert sorry if I'm missing something very easy but I stuck could not find any solution.
My code is almost identical with the code example code inside sqflite package page.

```
Future<bool> init(String requestGuid) async {
  bool onCreateDb = false;
  final Directory formsDirectory = await getApplicationDocumentsDirectory();
  this.dbPath = join(formsDirectory.path, '$cache.db');
  db = await openDatabase(this.dbPath, version: 1, onCreate: (Database newDb, int version) {
    onCreateDb = true;
    newDb.execute('''
  CREATE TABLE $requestGuid (
      ${K.itemId} TEXT PRIMARY KEY,
      ${K.requestGuid} TEXT,
      ${K.itemStatus} TEXT,
      ${K.itemComment} TEXT)
      ''');
  });
  return onCreateDb;
}
```

```
  Future<void> restoreDb() async {
    final List<dynamic> sqlRecords =
    await databaseProvider.restore({this.activeRequest[K.requestGuid]});
    for (Map<String, dynamic> m in sqlRecords) {
      this.formsCache.add(Map<String, dynamic>.from(m));
    }  }
```

```
E/SQLiteLog( 6217): (1) unrecognized token: "5c056459a3790"
I/flutter ( 6217): forms_model/restoreDb/log: DatabaseException(unrecognized token: "5c056459a3790" (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM 5c056459a3790) sql 'SELECT * FROM 5c056459a3790' args []}
I/flutter ( 6217): forms_model/restoreDb/trace: #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
I/flutter ( 6217): <asynchronous suspension>
I/flutter ( 6217): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
I/flutter ( 6217): #2      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183:15)
I/flutter ( 6217): #3      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite/src/database_mixin.dart:351:36)
I/flutter ( 6217): <asynchronous suspension>
I/flutter ( 6217): #4      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:290:22)
I/flutter ( 6217): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
I/flutter ( 6217): <asynchronous suspension>
I/flutter ( 6217): #6      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.tx
```

**Comment by alextekartik** [comment]
I guess your table name is 5c056459a3790. Since it starts with a number, maybe you should try to wrap it with `""`. Or maybe try to not make it starts with a number if you can (i.e. add a prefix). I have not tried this case yet so I'm not sure

**Comment by softronaut** [comment]
As I sense, it was a small thing. Thank you for both your reply and package Tekartik :)
