### ISSUE TITLE
How to insert a json string? got syntax error

### ISSUE THREAD

**Issue by jinfagang** [tekartik/sqflite#265]
Hi, I wanna insert a json string to db:

```
      currentNote.content = '{"insert":"RrrrrrrrZefyr Quick Start\n"}';

```
db service code:
```
int id = await db.transaction((transaction) {
      transaction.rawInsert(
          'INSERT into Notes(title, content, date, isImportant) VALUES ("${newNote.title}", "${newNote.content}", "${newNote.date.toIso8601String()}", ${newNote.isImportant == true ? 1 : 0});');
    });
```

I got syntax error here:

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=1 "near "insert": syntax error" UserInfo={NSLocalizedDescription=near "insert": syntax error}) sql 'INSERT into Notes(title, content, date, isImportant) VALUES ("placeholder", "{"insert":"RrrrrrrrZefyr Quick Start
"}", "2019-09-13T11:41:00.874040", 0);' args []}
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
#2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183:15)
#3      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite/src/database_mixin.dart:340:14)
#4      SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:275:26)
<asynchronous suspension>
#5      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite/src/database_mixin.dart:307:7)
#6      SqfliteDataba<…>
```

Seems json string has conflicts with query syntax.

**Comment by Parables** [comment]
I inserted json object by importing
 `import 'dart:convert';`
and then use the 
` json.encode(jsonObject)` and ` json.decode(jsonString)` to insert and retrieve my data

Hope it helps
