### ISSUE TITLE
It seems sqflite will occur error in flutter 1.10.7

### ISSUE THREAD

**Issue by heibor** [tekartik/sqflite#281]
I have upgraded my flutter from 1.9.4 to 1.10.7, before upgraded, my App is well, but there are some errors after I upgraded the flutter, it shows there error reporting:

```
E/flutter (11618): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (11618): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (11618): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (11618): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter (11618): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter (11618): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (11618): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #4      invokeMethod (package:sqflite/src/sqflite_impl.dart:20:13)
E/flutter (11618): #5      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:29:7)
E/flutter (11618): #6      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:24:35)
E/flutter (11618): #7      wrapDatabaseException (package:sqflite/src/exception_impl.dart:8:34)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #8      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
E/flutter (11618): #9      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:24:7)
E/flutter (11618): #10     SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:140:17)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #11     getDatabasesPath (package:sqflite/sqflite.dart:169:54)
E/flutter (11618): #12     dbPath (package:modesty/db_util.dart:23:52)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #13     initDB (package:modesty/db_util.dart:34:22)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #14     initApp (package:modesty/env.dart:44:9)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #15     main (package:modesty/main.dart:12:9)
E/flutter (11618): <asynchronous suspension>
E/flutter (11618): #16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (11618): #17     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (11618): #18     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (11618): #19     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (11618): #20     runZoned (dart:async/zone.dart:1500:12)
E/flutter (11618): #21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (11618): #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (11618): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (11618): 
```

I don't know if this is a compatibility issue.

**Comment by alextekartik** [comment]
It is a new restriction in Flutter, for any plugin. The solution is explained in the log:

```
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
if you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
```

I guess you (or a dependency) is calling sqflite before runApp is called. Simply add `WidgetsFlutterBinding.ensureInitialized()` in you main().
