### ISSUE TITLE
The application crashed after upgrading Flutter to v1.13.2 , after building apk release

### ISSUE THREAD

**Issue by VNAPNIC** [tekartik/sqflite#331]
The application crashed after upgrading Flutter to v1.13.2 , after building apk release

```
2019-12-18 10:47:28.757 9506-9566/? E/SQLiteDatabase: Error inserting path=/storage/emulated/0/app-development-release.apk
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: history.path (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:995)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2021)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1890)
        at com.amaze.filemanager.database.UtilsHandler.setPath(UtilsHandler.java:526)
        at com.amaze.filemanager.database.UtilsHandler.lambda$saveToDatabase$0$UtilsHandler(UtilsHandler.java:185)
        at com.amaze.filemanager.database.UtilsHandler$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by alextekartik** [comment]
That seems to come from a different application, see 'com.amaze.filemanager' in the stack trace. If you encounter an issue in your app, please try to wrap your dart code to catch the exception and post your code where the issue is seen.
