### ISSUE TITLE
Version 0.7.1 crashes on database init with following stack:

### ISSUE THREAD

**Issue by Norbert515** [tekartik/sqflite#34]
```
E/flutter ( 5025): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5025): NoSuchMethodError: Class 'List' has no instance method 'cast'.
E/flutter ( 5025): Receiver: _List len:1
E/flutter ( 5025): Tried calling: cast()
E/flutter ( 5025): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter ( 5025): #1      new QueryResultSet (package:sqflite/src/sqflite_impl.dart:69)
E/flutter ( 5025): #2      queryResultSetFromMap (package:sqflite/src/sqflite_impl.dart:41)
E/flutter ( 5025): #3      queryResultToList (package:sqflite/src/sqflite_impl.dart:52)
E/flutter ( 5025): #4      Database.rawQuery.<anonymous closure>.<anonymous closure> (package:sqflite/sqflite.dart:269)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #5      wrapDatabaseException (package:sqflite/src/exception.dart:48)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #6      Database.rawQuery.<anonymous closure> (package:sqflite/sqflite.dart:264)
E/flutter ( 5025): #7      SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:125)
E/flutter ( 5025): #8      Database.synchronized (package:sqflite/sqflite.dart:308)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #9      Database.rawQuery (package:sqflite/sqflite.dart:263)
E/flutter ( 5025): #10     Database.getVersion (package:sqflite/sqflite.dart:351)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #11     openDatabase.<anonymous closure> (package:sqflite/sqflite.dart:496)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #12     Database.inTransaction.<anonymous closure> (package:sqflite/sqflite.dart:335)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #13     SynchronizedLock._run.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:87)
E/flutter ( 5025): #14     _rootRun (dart:async/zone.dart:1126)
E/flutter ( 5025): #15     _CustomZone.run (dart:async/zone.dart:1023)
E/flutter ( 5025): #16     runZoned (dart:async/zone.dart:1501)
E/flutter ( 5025): #17     SynchronizedLock._run.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:85)
E/flutter ( 5025): #18     new Future.sync (dart:async/future.dart:222)
E/flutter ( 5025): #19     SynchronizedLock._run (package:synchronized/src/synchronized_impl.dart:84)
E/flutter ( 5025): #20     SynchronizedLock.synchronized.run (package:synchronized/src/synchronized_impl.dart:150)
E/flutter ( 5025): #21     SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:160)
E/flutter ( 5025): #22     Database.writeSynchronized (package:sqflite/sqflite.dart:319)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #23     Database.inTransaction (package:sqflite/sqflite.dart:327)
E/flutter ( 5025): #24     openDatabase (package:sqflite/sqflite.dart:495)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #25     BookDatabase.init (package:test_app/database.dart:27)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #26     Repository.init (package:test_app/data/repository.dart:26)
E/flutter ( 5025): <asynchronous suspension>
E/flutter ( 5025): #27     _SearchBookState.initState (package:test_app/pages/search_book_page.dart:84)
E/flutter ( 5025): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3711)
E/flutter ( 5025): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577)
E/flutter ( 5025): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
E/flutter ( 5025): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
E/flutter ( 5025): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
E/flutter ( 5025): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
E/flutter ( 5025): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3582)
E/flutter ( 5025): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577)
E/flutter ( 5025): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
E/flutter ( 5025): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
E/flutter ( 5025): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613)
E/flutter ( 5025): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
E/flutter ( 5025): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3582)
E/flutter ( 5025): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577)
E/flutter ( 5025): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
E/flutter ( 5025): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2678)
E/flutter ( 5025): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4588)
E/flutter ( 5025): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875)
E/flutter ( 5025): #46     Element.updateChild (package:flutter/src/widgets/f

```

**Comment by alextekartik** [comment]
Which flutter version are you using. I'm afraid 0.7.0 is only for beta+. Can you try to either upgrade flutter or downgrade sqlite (<0.7.0)?

**Comment by Norbert515** [comment]
Yes, I fixed it by downgrading to 0.6.1.
```
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (9 days ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```
 Looks like I'm using beta though.

**Comment by alextekartik** [comment]
Indeed that's weird. I made changes in this area to support dart 2.0.0 so it looks you're still seeing the pb. I need to investigate. Looks like cast is not defined for you in List although that should be the case in dart 2. I had similar issue in the past where the flutter cache was not built properly. you might also try to delete the flutter cache folder `flutter/bin/cache` and run `flutter doctor` again which should rebuild it. In flutter `bin/cache/pkg/sky_engine/lib/core/list.dart` there should be the the method `List<R> cast<R>();`

**Comment by alextekartik** [comment]
Do you still have the issue (after cleaning flutter, cache and build)? For beta (2.0.0dev+) I do recommend sqflite 0.8.2 and above though (0.6.1 should not work on it)

**Comment by VizGhar** [comment]
I've had exactly same problem. I've had to call the:
- `flutter upgrade` (upgrading from alpha version of flutter)
- `flutter doctor`
not sure whether `flutter/bin/cache` helped me as well, but I've managed to make it work

**Comment by Norbert515** [comment]
Sorry for the late response, upgrading flutter and sqflite to 0.8.2 fixed the problem, thanks!

**Comment by alextekartik** [comment]
Ok good, thanks for the confirmation. You're not the only one (me included) getting issue when upgrading (flutter, packages). `flutter clean` is our friend
