### ISSUE TITLE
Cast exception when running DELETE FROM table_name WHERE id IN [list_of_ids]

### ISSUE THREAD

**Issue by GyuriMajercsik** [tekartik/sqflite#371]
I would like to remove multiple rows by a single shot using the following SQL: 

`DELETE FROM table_name WHERE id IN list_of_ids` 

I get the following error: 

```
DatabaseException(java.lang.Long cannot be cast to java.lang.Integer) sql 'DELETE FROM table_name WHERE id IN ?' args [[6024123392343956179, 2988264080218449854, 831784125093042831]]}
I/flutter ( 4874): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:12:7)
I/flutter ( 4874): <asynchronous suspension>
I/flutter ( 4874): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
I/flutter ( 4874): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188:15)
I/flutter ( 4874): #3      SqfliteDatabaseMixin.txnRawUpdate.<anonymous closure> (package:sqflite/src/database_mixin.dart:388:14)
I/flutter ( 4874): #4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite/src/database_mixin.dart:307:22)
I/flutter ( 4874): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
I/flutter ( 4874): #6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:303:43)
I/flutter ( 4874): #7      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite/src/database_mixin.dart:325:7)
I/flutter ( 4874): #8      SqfliteDatabaseMixin.txnRawUpdate (package:sqflite/src/database_mixin.dart:387:12)
```

This is the exact code I'm using: 

```
  Future<void> deleteAll(List<int> ids) async {
    await _db.delete(
      _TABLE_NAME,
      where: '$_COLUMN_ID IN ?',
      whereArgs: [ids],
    );
  }
```

I'm using version 1.2.0

**Comment by GyuriMajercsik** [comment]
I found a workaround: 

```
    await _db.rawDelete(
      'DELETE FROM $_TABLE_NAME '
      'WHERE $_COLUMN_ID '
      'IN (${ids.join(',')})',
    );
```

Please close if you consider this not a bug.

**Comment by alextekartik** [comment]
Indeed this is as expected

**Comment by omidraha** [comment]
@alextekartik 
Is this correct code to delete all records by ids?

```dart
    await db.rawDelete(
      'DELETE FROM my_table '
      'WHERE id '
      'IN (${ids.join(',')})',
    );
```
And is there a way to use [db.delete](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#delete)  instead?

**Comment by alextekartik** [comment]
@omidraha  Yes that is correct (assuming the ids are integers).

This is equivalent tp: `await db.delete('my_table', where: 'id IN (${ids.join(',')})');`
