### ISSUE TITLE
ERROR at :app:processDebugManifest

### ISSUE THREAD

**Issue by icnahom** [tekartik/sqflite#380]
**The Error**
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: D:\Code\Flutter\gebi\build\sqflite\intermediates\library_manifest\debug\AndroidManifest.xml (The system cannot find the path specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 4s
[!] Gradle threw an error while trying to update itself. Retrying the update...

**Added dependencies** 
`sqflite: 1.2.1`
`path: 1.6.4`

**Gradle Version**
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

**Comment by icnahom** [comment]
**Flutter Doctor Verbose**
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (11 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:/Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM G800F • 192.168.137.36:5555 • android-arm • Android 6.0.1 (API 23)

• No issues found!

**Comment by icnahom** [comment]
**Running with --verbose**
D:\Code\Flutter\gebi>flutter run --verbose
[  +78 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +301 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +31 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +213 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +36 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +238 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[ +106 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[ +197 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +316 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +164 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +355 ms] executing: C:\Android\platform-tools\adb.exe devices -l
[  +93 ms] Exit code 0 from: C:\Android\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           192.168.137.36:5555    device product:kminiltexx model:SM_G800F device:kminilte transport_id:4
[  +57 ms] C:\Android\platform-tools\adb.exe -s 192.168.137.36:5555 shell getprop
[ +318 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +226 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.1\
[ +690 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.1\
[+1147 ms] Generating D:\Code\Flutter\gebi\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +181 ms] ro.hardware = universal3470
[   +2 ms] ro.build.characteristics = phone
[ +166 ms] Launching lib\main.dart on SM G800F in debug mode...
[  +40 ms] executing: C:\Android\platform-tools\adb.exe -s 192.168.137.36:5555 shell -x logcat -v time -t 1
[ +629 ms] Exit code 0 from: C:\Android\platform-tools\adb.exe -s 192.168.137.36:5555 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           02-22 18:40:32.989 W/BugleRcsEngine(10952): [22131] szm.c: process intent: android.intent.action.SIM_STATE_CHANGED
[  +26 ms] executing: C:\Android\platform-tools\adb.exe version
[   +5 ms] executing: C:\Android\platform-tools\adb.exe -s 192.168.137.36:5555 logcat -v time -T 02-22 18:40:32.989
[ +305 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.6-6198805
                    Installed as C:\Android\platform-tools\adb.exe
[  +14 ms] executing: C:\Android\platform-tools\adb.exe start-server
[ +233 ms] Building APK
[ +138 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[  +39 ms] Using gradle from D:\Code\Flutter\gebi\android\gradlew.bat.
[  +96 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+1306 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +9 ms] executing: [D:\Code\Flutter\gebi\android\] D:\Code\Flutter\gebi\android\gradlew.bat -Pverbose=true -Ptarget=D:\Code\Flutter\gebi\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[+11441 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[  +89 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :sqflite:preBuild UP-TO-DATE
[        ] > Task :sqflite:preDebugBuild UP-TO-DATE
[        ] > Task :sqflite:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :sqflite:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[ +105 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +90 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :sqflite:compileDebugShaders UP-TO-DATE
[        ] > Task :sqflite:generateDebugAssets UP-TO-DATE
[ +135 ms] > Task :sqflite:packageDebugAssets UP-TO-DATE
[  +59 ms] > Task :app:mergeDebugAssets
[+29984 ms] > Task :app:copyFlutterAssetsDebug
[ +915 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +94 ms] > Task :sqflite:generateDebugResValues UP-TO-DATE
[   +4 ms] > Task :sqflite:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :sqflite:generateDebugResources UP-TO-DATE
[   +2 ms] > Task :sqflite:packageDebugResources UP-TO-DATE
[ +283 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +90 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +2 ms] > Task :sqflite:checkDebugManifest UP-TO-DATE
[   +2 ms] > Task :sqflite:processDebugManifest UP-TO-DATE
[   +8 ms] > Task :app:processDebugManifest FAILED
[  +88 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:processDebugManifest'.
[   +2 ms] > com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException:
D:\Code\Flutter\gebi\build\sqflite\intermediates\library_manifest\debug\AndroidManifest.xml (The system cannot find the path specified)
[   +5 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[ +112 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 42s
[   +1 ms] 21 actionable tasks: 4 executed, 17 up-to-date
[ +598 ms] Running Gradle task 'assembleDebug'... (completed in 45.6s)
[  +20 ms] [!] Gradle threw an error while trying to update itself. Retrying the update...
[  +13 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +10 ms] Using gradle from D:\Code\Flutter\gebi\android\gradlew.bat.
[   +3 ms] executing: [D:\Code\Flutter\gebi\android\] D:\Code\Flutter\gebi\android\gradlew.bat -Pverbose=true -Ptarget=D:\Code\Flutter\gebi\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[+8947 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[  +16 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :sqflite:preBuild UP-TO-DATE
[   +4 ms] > Task :sqflite:preDebugBuild UP-TO-DATE
[   +5 ms] > Task :sqflite:compileDebugAidl NO-SOURCE
[  +81 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +9 ms] > Task :sqflite:packageDebugRenderscript NO-SOURCE
[   +4 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +3 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[ +189 ms] > Task :app:cleanMergeDebugAssets
[  +81 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +12 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +2 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[   +2 ms] > Task :sqflite:compileDebugShaders UP-TO-DATE
[   +3 ms] > Task :sqflite:generateDebugAssets UP-TO-DATE
[   +6 ms] > Task :sqflite:packageDebugAssets UP-TO-DATE
[  +11 ms] > Task :app:mergeDebugAssets
[ +861 ms] > Task :app:copyFlutterAssetsDebug
[   +7 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +4 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +82 ms] > Task :sqflite:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :sqflite:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :sqflite:generateDebugResources UP-TO-DATE
[   +2 ms] > Task :sqflite:packageDebugResources UP-TO-DATE
[ +400 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +177 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +6 ms] > Task :sqflite:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :sqflite:processDebugManifest UP-TO-DATE
[  +60 ms] > Task :app:processDebugManifest FAILED
[  +10 ms] 21 actionable tasks: 4 executed, 17 up-to-date
[   +2 ms] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[   +7 ms] Execution failed for task ':app:processDebugManifest'.
[  +23 ms] > com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException:
D:\Code\Flutter\gebi\build\sqflite\intermediates\library_manifest\debug\AndroidManifest.xml (The system cannot find the path specified)
[  +19 ms] * Try:
[  +33 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[  +99 ms] * Get more help at https://help.gradle.org
[  +30 ms] BUILD FAILED in 9s
[ +633 ms] Running Gradle task 'assembleDebug'... (completed in 11.9s)
[   +4 ms] [!] Gradle threw an error while trying to update itself. Retrying the update...
[  +19 ms] "flutter run" took 62,439ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:431:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by icnahom** [comment]
Fixed by bringing down the Gradle Version to gradle-5.4.1-all.zip
