### ISSUE TITLE
sqlfile.update() error on unique constraint

### ISSUE THREAD

**Issue by marciokrul** [tekartik/sqflite#427]
When I add the records with the insert option it works perfectly (sqfile.insert ("table", data),
but when choosing the update option return a unique constraint error.

sqlfile version 1.3.0
Flutter 1.12.13+hotfix.10-pre.1 • channel stable
Framework • revision 1a99c2e386 (18 hours ago) • 2020-04-30 18:05:35 -0300
Engine • revision af51afceb8
Tools • Dart 2.7.2

ERROR MESSAGE=> "UNIQUE constraint failed: jobActivity(code 1555 [1555])"

This is a my table;
CREATE TABLE IF NOT EXISTS jobActivity (
"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
"activeDate"	TEXT,
"Job"	TEXT,
"classJob" TEXT,
"descriptionWork"	TEXT, ' +
"hoursExpended"	REAL, 
"listOfResolutions"	TEXT,
"onWeb"	INTEGER DEFAULT 0,
"onWebDate"	TEXT,
"createdDate"	TEXT,
"userName"	TEXT);

UPDATE COMMAND:
_db
        .update(
            'jobActivity',
            job,
            conflictAlgorithm: ConflictAlgorithm.fail)
        .then((val) {.....

UPDATE DESCRIPTION:

"UPDATE OR FAIL jobActivity SET id = ?, activeDate= ?, Job = ?, classJob = ?, descriptionWork = ?, hoursExpended = ?, listOfResolutions = ?, onWebDate = NULL, onWeb = NULL, userName = NULL, createdDate = ?"
args[6,'20200106','Fix Bugs', '{id:1,description:bugs}','Review beta.class', '0.2', '[{id:5,description: refactor},{id:1, description:publush}, '20200501']'];

Error E/S :
E/flutter (30273): #0      jobPrincipalBloc.onSubmitting 
package:agro_mobile/…/xxxxxxxxxxxxxx/xxxxxxx/xxxxxx.dart:131
E/flutter (30273): #1      _asyncErrorWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:80:45)
E/flutter (30273): #2      _rootRunBinary  (dart:async/zone.dart:1146:38)
E/flutter (30273): #3      _CustomZone.runBinary  (dart:async/zone.dart:1039:19)
E/flutter (30273): #4      _FutureListener.handleError  (dart:async/future_impl.dart:153:20)
E/flutter (30273): #5      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:692:47)
E/flutter (30273): #6      Future._propagateToListeners  (dart:async/future_impl.dart:713:24)
E/flutter (30273): #7      Future._completeError  (dart:async/future_impl.dart:532:5)
E/flutter (30273): #8      _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:38:15)
E/flutter (30273): #9      jobPrincipalBloc.Update (package:zzzzzzz.dart)
E/flutter (30273): #10     _asyncErrorWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:80:45)
E/flutter (30273): #11     _rootRunBinary  (dart:async/zone.dart:1146:38)
E/flutter (30273): #12     _CustomZone.runBinary  (dart:async/zone.dart:1039:19)
E/flutter (30273): #13     _FutureListener.handleError  (dart:async/future_impl.dart:153:20)
E/flutter (30273): #14     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:692:47)
E/flutter (30273): #15     Future._propagateToListeners  (dart:async/future_impl.dart:713:24)
E/flutter (30273): #16     Future._completeError  (dart:async/future_impl.dart:532:5)

**Comment by marciokrul** [comment]
Found a simple solution use where args exemple:

UPDATE COMMAND:
_db
.update(
'jobActivity',
job,
 where: "id = ?",
 whereArgs: ["6"],
conflictAlgorithm: ConflictAlgorithm.fail).
