### ISSUE TITLE
FATAL Exception: Sqflite

### ISSUE THREAD

**Issue by WonderProgrammer** [tekartik/sqflite#44]
```
FATAL EXCEPTION: Sqflite
Process: com.vendetta.flutterapp, PID: 4816
java.lang.IllegalArgumentException: the bind value at index 1 is null
            at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1401)
android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1340)
at com.tekartik.sqflite.SqflitePlugin.query(SqflitePlugin.java:511)
at com.tekartik.sqflite.SqflitePlugin.access$200(SqflitePlugin.java:52)
at com.tekartik.sqflite.SqflitePlugin$1.run(SqflitePlugin.java:357)
at android.os.Handler.handleCallback(Handler.java:819)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)
```
I've got this error when i tried to store some data inside the database. This is the function were the error was thrown:
```
Future datenSpeicher() async{
      Datenbank db = new Datenbank();
      await db.oeffnen();

      Rezept rezept = new Rezept();
      rezept.name = name_gespeichert;
      rezept.personen = anzahl_gespeichert;

      print(rezept.name+" "+rezept.personen.toString());

      rezept = await db.einfuegenRezept(rezept); //on this line was the error
    }
```

To add some data inside the database I use this function:
```
Future<Rezept> einfuegenRezept(Rezept rezept) async{
    var count = Sqflite.firstIntValue(await _db.rawQuery("SELECT COUNT(*) FROM rezept WHERE _ID = ?", [rezept.id]));
    if(count == 0){
      rezept.id = await _db.insert(tableRezept, rezept.toMap());
    } else{
      //await _db.update(tableRezept, rezept.toMap(), where: "id = ?", whereArgs: [rezept.id]);
    }

    return rezept;
  }
```

I hope that somebody has a solution to my problem! :-D

**Comment by alextekartik** [comment]
I will take a look. As the error said `java.lang.IllegalArgumentException: the bind value at index 1 is null`, it seems that you have a null value in your map. SQLite does not support that (yes it is a pain) so you have to explicitely use the new keyword in your update raw query. I will try to reproduce the issue and see whether I can find a solution tomorrow

**Comment by WonderProgrammer** [comment]
Thanks for the solution, that worked out for me.
