### ISSUE TITLE
Error on running? how to solve this

### ISSUE THREAD

**Issue by akhilprogrammer** [tekartik/sqflite#484]
hei i got errors on running i use several packages? is it any problem with that. below i give compelete package details

  cupertino_icons: ^0.1.3
  sqflite:
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  charts_flutter: ^0.9.0
  path_provider: ^1.6.11
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  flutter_isolate: ^1.0.0+14
  sensors: ^0.4.2+2

And my error is this

E/flutter ( 5165): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter ( 5165): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 5165): <asynchronous suspension>
E/flutter ( 5165): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 5165): #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter ( 5165): #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
E/flutter ( 5165): #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
E/flutter ( 5165): #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter ( 5165): #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter ( 5165): #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
E/flutter ( 5165): #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
E/flutter ( 5165): #9      SqfliteDatabaseFactoryMixin.fixPath (package:sqflite_common/src/factory_mixin.dart:164:27)
E/flutter ( 5165): #10     SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:72:20)
E/flutter ( 5165): #11     ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:35:24)
E/flutter ( 5165): #12     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 5165): #13     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 5165): #14     _runZoned (dart:async/zone.dart:1619:10)
E/flutter ( 5165): #15     runZoned (dart:async/zone.dart:1539:10)
E/flutter ( 5165): #16     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:34:24)
E/flutter ( 5165): #17     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 5165): #18     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:30:17)
E/flutter ( 5165): #19     SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite_common/src/factory_mixin.dart:71:17)
E/flutter ( 5165): #20     openDatabase (package:sqflite/sqflite.dart:152:26)
E/flutter ( 5165): #21     main (package:falldectapp/main.dart:34:9)
E/flutter ( 5165): <asynchronous suspension>
E/flutter ( 5165): #22     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter ( 5165): #23     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 5165): #24     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 5165): #25     _runZoned (dart:async/zone.dart:1619:10)
E/flutter ( 5165): #26     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter ( 5165): #27     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter ( 5165): #28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 5165): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 5165):

**Comment by alextekartik** [comment]
(I have edited your comment to add backticks as otherwise each #number will trigger a link to other unrelated bugs)

There are several bugs about [similar issues](https://github.com/tekartik/sqflite/issues?q=is%3Aissue+MissingPluginException) that you can take a look as well as a dedicated section on how to (try to) solve this issue: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missingpluginexception

What is likely happening is that plugin registration fail. Sometimes debugging can help.

**Comment by OptisolSivaG** [comment]
https://github.com/tekartik/sqflite/issues/452#issuecomment-3023674010

TRY THIS SOLUTION
