### ISSUE TITLE
onUpgrade not creating new table? 

### ISSUE THREAD

**Issue by samMason20** [tekartik/sqflite#485]
Hi, I am currently developing a workout app and I am attempting to save each created workout in a new table. Initially the table workout0 is created with no problems and data is stored and retrieved fine. But when I attempt to increase the version number it appears as though the onUpgrade function does not run as I get an error telling me the table workout1 doesn't exisit. 
This is the function that is called when the "Done" button is pressed from the bottom navigation bar, with tableId defined as such.
```
List<int> tableId = <int> [ ];
```  

```
savedWorkout(int index) async{

    await Sqflite.devSetDebugModeOn(true);

    if (index == 0) {
      print('Done');

      int tbid = tableId.length;

      var database = openDatabase(
        join(await getDatabasesPath(), 'workout_database.db'),
        onCreate: (db, version) {
          db.execute(
            "CREATE TABLE workout0(id INTEGER PRIMARY KEY, sets INTEGER, rep INTEGER, title TEXT, weight INTEGER, setNum INTEGER, rest INTEGER)"
          );
        },
        version: tbid+1,
        onUpgrade: (Database db, int oldVersion, int newVersion) {
          if(oldVersion<newVersion) {
            db.execute(
                "CREATE TABLE workout$tbid(id INTEGER PRIMARY KEY, sets INTEGER, rep INTEGER, title TEXT, weight INTEGER, setNum INTEGER, rest INTEGER)"
            );
          }
        },
        onOpen: (Database db) async{
          print('db version ${await db.getVersion()}');
        },
      );

      // Define a function that inserts exercises into the database
      Future<void> insertData(ExerciseCard exerciseCard) async {
        
        Database db = await database;

        await db.insert(
          'workout$tbid',
          exerciseCard.toMap(),
        );
      }

      Future<List<ExerciseCard>> woExercises() async {
        
        Database db = await database;

        // Query the table for all the Exercises.
        List<Map<String, dynamic>> maps = await db.query('workout$tbid');

        // Convert the List<Map<String, dynamic> into a List<ExerciseCard>.
        return List.generate(maps.length, (i) {
          return ExerciseCard(
              id: maps[i]['id'],
              sets: maps[i]['sets'],
              rep: maps[i]['rep'],
              title: maps[i]['title'],
              weight: maps[i]['weight'],
              setNum: maps[i]['setNum'],
              rest: maps[i]['rest']
          );
        });
      }

      dbdata.forEach((element) async{
        await insertData(element);
      });

      print(await woExercises());

      tableId.add(1);

    }
    else{
      print ('PlaceHolder');
    }
  }

```
The if statement simply ensures to only save the workout for a particular item press in the navigation bar. For completeness here is the function being called.
```
bottomNavigationBar: BottomNavigationBar(
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.send),
            title: Text('Done'),
            ),
          BottomNavigationBarItem(
            icon: Icon(Icons.category),
            title: Text('PlaceHolder')
          )
        ],
        onTap: savedWorkout,
      ),
    );
```
I have tried numerous alterations to get this to work but nothing I have tried has helped. I wiped the data from the android emulator and ran the code again, adding a single 'Timer' class instance into the first table, workout0 and attempting to do so for the second table, workout1, these are the errors I get. 
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,393ms.
I/zygote  ( 6741): Do partial code cache collection, code=30KB, data=27KB
I/zygote  ( 6741): After code cache collection, code=30KB, data=27KB
I/zygote  ( 6741): Increasing code cache capacity to 128KB
I/flutter ( 6741): Done
D/Sqflite ( 6741): [1,main(2)] starting threadThread[Sqflite,5,main] priority 10
D/Sqflite ( 6741): [1,main(2)] opened 1 /data/user/0/com.samuelm.workoutbuilder/databases/workout_database.db
D/Sqflite ( 6741): [1,Sqflite(252)] opened 1 /data/user/0/com.samuelm.workoutbuilder/databases/workout_database.db
D/Sqflite ( 6741): [1,Sqflite(252)] PRAGMA user_version
D/Sqflite ( 6741): [1,Sqflite(252)] BEGIN EXCLUSIVE
D/Sqflite ( 6741): [1,Sqflite(252)] PRAGMA user_version
D/Sqflite ( 6741): [1,Sqflite(252)] CREATE TABLE workout0(id INTEGER PRIMARY KEY, sets INTEGER, rep INTEGER, title TEXT, weight INTEGER, setNum INTEGER, rest INTEGER)
D/Sqflite ( 6741): [1,Sqflite(252)] PRAGMA user_version = 1
D/Sqflite ( 6741): [1,Sqflite(252)] COMMIT
D/Sqflite ( 6741): [1,Sqflite(252)] PRAGMA user_version
I/flutter ( 6741): db version 1
D/Sqflite ( 6741): [1,Sqflite(252)] INSERT INTO workout0 (id, sets, rep, title, weight, setNum, rest) VALUES (?, ?, ?, ?, ?, ?, ?) [0, 0, 0, Timer, 0, 0, 4]
D/Sqflite ( 6741): [1,Sqflite(252)] inserted 0
D/Sqflite ( 6741): [1,Sqflite(252)] SELECT * FROM workout0
I/flutter ( 6741): [ex{id: 0, rep: 0, title:Timer, setNum: 0}]
I/flutter ( 6741): Done
D/Sqflite ( 6741): [1,Sqflite(252)] INSERT INTO workout1 (id, sets, rep, title, weight, setNum, rest) VALUES (?, ?, ?, ?, ?, ?, ?) [0, 0, 0, Timer, 0, 0, 4]
E/SQLiteLog( 6741): (1) no such table: workout1
D/Sqflite ( 6741): [1,Sqflite(252)] SELECT * FROM workout1
E/SQLiteLog( 6741): (1) no such table: workout1
E/flutter ( 6741): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(no such table: workout1 (code 1): , while compiling: INSERT INTO workout1 (id, sets, rep, title, weight, setNum, rest) VALUES (?, ?, ?, ?, ?, ?, ?)) sql 'INSERT INTO workout1 (id, sets, rep, title, weight, setNum, rest) VALUES (?, ?, ?, ?, ?, ?, ?)' args [0, 0, 0, Timer, 0, 0, 4]}
E/flutter ( 6741): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 6741): <asynchronous suspension>
E/flutter ( 6741): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter ( 6741): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
E/flutter ( 6741): #3      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:383:14)
E/flutter ( 6741): #4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:327:22)
E/flutter ( 6741): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 6741): #6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:323:33)
E/flutter ( 6741): #7      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:345:7)
E/flutter ( 6741): #8      SqfliteDatabaseMixin.txnRawInsert (package:sqflite_common/src/database_mixin.dart:382:12)
E/flutter ( 6741): #9      SqfliteDatabaseExecutorMixin.rawInsert (package:sqflite_common/src/database_mixin.dart:50:15)
E/flutter ( 6741): #10     SqfliteDatabaseExecutorMixin.insert (package:sqflite_common/src/database_mixin.dart:60:12)
E/flutter ( 6741): #11     _NewWorkoutState.savedWorkout.insertData (package:workoutbuilder/pages/new_workout.dart:188:18)
E/flutter ( 6741): <asynchronous suspension>
E/flutter ( 6741): #12     _NewWorkoutState.savedWorkout.insertData (package:workoutbuilder/pages/new_workout.dart)
E/flutter ( 6741): #13     _NewWorkoutState.savedWorkout.<anonymous closure> (package:workoutbuilder/pages/new_workout.dart:218:25)
E/flutter ( 6741): #14     List.forEach (dart:core-patch/growable_array.dart:282:8)
E/flutter ( 6741): #15     _NewWorkoutState.savedWorkout (package:workoutbuilder/pages/new_workout.dart:217:14)
E/flutter ( 6741): #16     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6741): #17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6741): #18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6741): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6741): #20     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6741): #21     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 6741): #22     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 6741): #23     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6741): #24     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6741): #25     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6741): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6741): #27     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6741): #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6741): 
E/flutter ( 6741): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(no such table: workout1 (code 1): , while compiling: SELECT * FROM workout1) sql 'SELECT * FROM workout1' args []}
E/flutter ( 6741): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 6741): <asynchronous suspension>
E/flutter ( 6741): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter ( 6741): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
E/flutter ( 6741): #3      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:394:36)
E/flutter ( 6741): #4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:327:22)
E/flutter ( 6741): #5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 6741): <asynchronous suspension>
E/flutter ( 6741): #6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:323:33)
E/flutter ( 6741): #7      SqfliteDatabaseMixin.txnRawQuery (package:sqflite_common/src/database_mixin.dart:393:12)
E/flutter ( 6741): #8      SqfliteDatabaseExecutorMixin._rawQuery (package:sqflite_common/src/database_mixin.dart:126:15)
E/flutter ( 6741): #9      SqfliteDatabaseExecutorMixin.query (package:sqflite_common/src/database_mixin.dart:110:12)
E/flutter ( 6741): #10     _NewWorkoutState.savedWorkout.woExercises (package:workoutbuilder/pages/new_workout.dart:199:52)
E/flutter ( 6741): <asynchronous suspension>
E/flutter ( 6741): #11     _NewWorkoutState.savedWorkout.woExercises (package:workoutbuilder/pages/new_workout.dart)
E/flutter ( 6741): #12     _NewWorkoutState.savedWorkout (package:workoutbuilder/pages/new_workout.dart:221:30)
E/flutter ( 6741): #13     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6741): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6741): #15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6741): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6741): #17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6741): #18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 6741): #19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 6741): #20     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6741): #21     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6741): #22     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6741): #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6741): #24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6741): #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6741): 

```
Thank you in advance for any help with this it is much appreciated and sorry if anything is missing/wrong I am very new to github and this plugin!

**Comment by davidmartos96** [comment]
What are you trying to achieve with a separate table for each workout? That looks like it goes against the common relational database schemes.
Database upgrades are normally used when you need to add a new column (workout_type) or when you need to create new tables.
In your case you would simply save different workouts in the same Workouts table. Each will have a different workout id. The exercises table would then have a column like workout_id, which will tell to which workout it belongs. 
I'd encourage you to look up some tutorials about Relational Database concepts (tables, schema, primary keys, foreign keys...)

Regarding your issue, I don't think it would help much to look into why is not working as you expect, because of how are you using the plugin. 
Things to point out:
- The database should normally be opened once at the start of the app. You are opening each time you call `savedWorkout`
- The database version should be a simple constant number in your app. 1, 2, 3. No need to use a separate tableId list.
- Save all workouts in the same table
