### ISSUE TITLE
DatabaseException(database_closed) - sqflite: ^1.3.2+1

### ISSUE THREAD

**Issue by v7lin** [tekartik/sqflite#553]
pubspec.yaml

```yaml
  sqflite: ^1.3.2+1
```

log
```shell
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: DatabaseException(database_closed)
flutter: 
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
#2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
#3      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:394:36)
#4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:327:22)
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
<asynchronous suspension>
#6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:323:33)
#7      SqfliteDatabaseMixin.txnRawQuery (package:sqflite_common/src/database_mixin.dart:393:12)
#8      SqfliteDatabaseExecutorMixin._rawQuery (package:sqflite_common/src/database_mixin.dart:126:15)
#9      SqfliteDatabaseExecutorMixin.query (pac<…>
flutter: ----------------------------------------------------
```

HomeModel
```dart
    BookShelfModel bookShelfModel = BookShelfModel.of(context);
    await Future.wait<dynamic>(<Future<dynamic>>[
      bookShelfModel.startScan(),
      bookShelfModel.fetchBulkRenew(),
      bookShelfModel.fetchReadingLogs(),
    ]);
```

BookShelfModel
```dart
  Future<void> startScan() async {
    List<String> bookIds = await BookShelfDbHelper.shared().retrieveBookIds();
    if (bookIds?.isNotEmpty ?? false) {
      // TODO
    }
  }
  Future<void> fetchBulkRenew() async {
    List<String> bookIds = await BookShelfDbHelper.shared().retrieveBookIds();
    if (bookIds?.isNotEmpty ?? false) {
      // TODO
    }
  }

  Future<void> fetchReadingLogs() async {
    List<String> bookIds = await BookShelfDbHelper.shared().retrieveBookIds();
    if (bookIds?.isNotEmpty ?? false) {
      // TODO
    }
  }
```

BookShelfDbHelper

```dart
import 'package:fnovel/services/database/sqlite_open_helper.dart';
import 'package:sqflite/sqlite_api.dart';

class BookShelfDbHelper extends SimpleSQLiteOpenHelper {
  BookShelfDbHelper._() : super('book_shelf.db', 1);

  factory BookShelfDbHelper.shared() {
    return _instance;
  }

  static final BookShelfDbHelper _instance = BookShelfDbHelper._();

  static const String _kTableName = 'book_shelf';

  static const List<String> _kColumns = <String>[
    'book_id',
    'create_time',
  ];

  static const int _kColumnBookId = 0;
  static const int _kColumnCreateTime = 1;

  @override
  Future<void> onCreate(Database db, int version) {
    return db.execute('''
    create table if not exists $_kTableName (
      ${_kColumns[_kColumnBookId]} text primary key, 
      ${_kColumns[_kColumnCreateTime]} integer
    )
    ''');
  }

  @override
  Future<void> onUpgrade(Database db, int oldVersion, int newVersion) async {
    // do nothing
  }

  Future<List<String>> retrieveBookIds() async {
    Database db = await getReadableDatabase();
    try {
      List<Map<String, dynamic>> result = await db.query(
        _kTableName,
        columns: <String>[_kColumns[_kColumnBookId]],
        orderBy: '${_kColumns[_kColumnCreateTime]} DESC',
      );
      return result.map((Map<String, dynamic> map) => map[_kColumns[_kColumnBookId]] as String).toList();
    } finally {
      await closeQuietly(db);
    }
  }
}
```

SimpleSQLiteOpenHelper
```
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as path;
import 'package:sqflite/sqflite.dart';
export 'package:sqflite/src/database_mixin.dart';

abstract class SQLiteOpenHelper {
  SQLiteOpenHelper(
    this.name,
    this.version,
  );

  @protected
  final String name;
  @protected
  final int version;

  bool _initFlag = false;

  @protected
  Future<Database> _getDatabaseLocked({
    bool readOnly = false,
  }) async {
    Database database = await openDatabase(
      path.join(await getDatabasesPath(), name),
      version: version,
      onConfigure: onConfigure,
      onCreate: onCreate,
      onUpgrade: onUpgrade,
      onDowngrade: onDowngrade,
      onOpen: onOpen,
      readOnly: readOnly,
    );
    return database;
  }

  @protected
  Future<Database> getWritableDatabase() {
    return _getDatabaseLocked();
  }

  @protected
  Future<Database> getReadableDatabase() async {
    if (!_initFlag) {
      _initFlag = true;
      await _getDatabaseLocked(); // 第一次打开不能为 true
    }
    return await _getDatabaseLocked(readOnly: true);
  }

  @protected
  Future<void> onConfigure(Database db);

  @protected
  Future<void> onCreate(Database db, int version);

  @protected
  Future<void> onUpgrade(Database db, int oldVersion, int newVersion);

  @protected
  Future<void> onDowngrade(Database db, int oldVersion, int newVersion);

  @protected
  Future<void> onOpen(Database db);

  @protected
  Future<void> close(Database db) {
    return db?.close();
  }

  @protected
  Future<void> closeQuietly(Database db) async {
    try {
      await db?.close();
    } catch (e) {
      // do nothing
    }
  }
}

abstract class SimpleSQLiteOpenHelper extends SQLiteOpenHelper {
  SimpleSQLiteOpenHelper(String name, int version) : super(name, version);

  @protected
  @override
  Future<void> onConfigure(Database db) async {}

  @protected
  @override
  Future<void> onOpen(Database db) async {}

  @protected
  @override
  Future<void> onDowngrade(Database db, int oldVersion, int newVersion) async {}
}
```

**Comment by alextekartik** [comment]
I recommend keeping the database open. Otherwise make sure you have a global mutex for all open/read/write/close operation to avoid race conditions
