### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by arnold-parge** [tekartik/sqflite#58]
I suddenly came across this error.
It works only for the first time, then it gives error: **database is locked**.
below is what I see in the terminal:

```
E/SQLiteDatabase( 6785): Failed to open database '/data/user/0/com.arnold.knowbuddy/app_flutter/demo.db'.
E/SQLiteDatabase( 6785): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
E/SQLiteDatabase( 6785): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:711)
E/SQLiteDatabase( 6785): 	at com.tekartik.sqflite.SqflitePlugin$Database.open(SqflitePlugin.java:805)
E/SQLiteDatabase( 6785): 	at com.tekartik.sqflite.SqflitePlugin$Database.access$900(SqflitePlugin.java:796)
E/SQLiteDatabase( 6785): 	at com.tekartik.sqflite.SqflitePlugin.onOpenDatabaseCall(SqflitePlugin.java:682)
E/SQLiteDatabase( 6785): 	at com.tekartik.sqflite.SqflitePlugin.onMethodCall(SqflitePlugin.java:779)
E/SQLiteDatabase( 6785): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/SQLiteDatabase( 6785): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/SQLiteDatabase( 6785): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/SQLiteDatabase( 6785): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/SQLiteDatabase( 6785): 	at android.os.Looper.loop(Looper.java:147)
E/SQLiteDatabase( 6785): 	at android.app.ActivityThread.main(ActivityThread.java:6637)
E/SQLiteDatabase( 6785): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteDatabase( 6785): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/SQLiteDatabase( 6785): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/flutter ( 6785): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6785): DatabaseException(database is locked (code 5): , while compiling: PRAGMA journal_mode)
E/flutter ( 6785): #0      wrapDatabaseException (package:sqflite/src/exception.dart:82:7)
E/flutter ( 6785): <asynchronous suspension>
E/flutter ( 6785): #1      SqfliteDatabase._openDatabase (package:sqflite/src/database.dart:458:12)
E/flutter ( 6785): #2      SqfliteDatabase.open (package:sqflite/src/database.dart:506:28)
E/flutter ( 6785): <asynchronous suspension>
E/flutter ( 6785): #3      openDatabase (package:sqflite/src/database.dart:610:19)
E/flutter ( 6785): #4      openDatabase (package:sqflite/sqflite.dart:280:10)
E/flutter ( 6785): #5      dbInit (package:knowbuddy/backend/database.dart:20:22)
E/flutter ( 6785): <asynchronous suspension>
E/flutter ( 6785): #6      _HomePageState.initState (package:knowbuddy/pages/home_page.dart:134:5)
E/flutter ( 6785): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
E/flutter ( 6785): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 6785): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 6785): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 6785): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 6785): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 6785): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
E/flutter ( 6785): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
E/flutter ( 6785): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
E/flutter ( 6785): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
E/flutter ( 6785): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 6785): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 6785): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 6785): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
E/flutter ( 6785): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 6785): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 6785): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 6785): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 6785): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 6785): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 6785): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 6785): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 6785): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 6785): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 6785): #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:

```

**flutter doctor**

```

[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.


```

**Comment by alextekartik** [comment]
Thanks for the note. I did encounter this issue on Android. It seems that this could happen if you have more than one connection to the database (See some notes about that here: https://stackoverflow.com/questions/7930139/android-database-locked). Are you sure that you have opened your database only once or that if you open it twice that you properly closed it before. I cannot tell by your stack trace whether dbInit/openDatabase is called multiple times. Personally I typically have one global reference Database in my flutter application to avoid such issue (especially during hot reload)

**Comment by arnold-parge** [comment]
@alextekartik I have called the **closeDB** function on the dispose of home page. There could be a scenario that I directly closed the app from the recent apps list which means that the home page was not disposed and the database was not closed. When I reopened the app, app was trying to open the DB which is still not closed. Well I can't tell my user to properly close the app only by pressing back button.

What do I do in such case?

**Comment by arnold-parge** [comment]
Okay, by [this link](https://stackoverflow.com/questions/7930139/android-database-locked) I think for every transaction I should open the DB, solve query and immediately close it. This may solve the problem!!

**Comment by alextekartik** [comment]
@arnold-parge Personnally I never close the db and keep a global reference to it and so far never got the database lock issue (I had lock issue when I tried to have local reference and try to open/close while in a page and fast reload was sometimes loosing this reference). That is what Android application typically do, they open the db when needed and keep it open. When the application quit, the database is closed automatically.

I don't see your code so cannot tell whether your initDB/closeDB function can have race-condition issues.

> PS: Next time when you comment, please mention so that I can get notified and respond immediately. Thanks!

You can also subscribe to this issue to get notified even if someone comments on it and does not notify you

**Comment by tsun424** [comment]
Hi @alextekartik , do you know what the behaviour is in iOS for `When the application quit, the database is closed automatically.`? Will it be closed automatically in iOS as well? Thanks.

**Comment by alextekartik** [comment]
That is what I have read (and understood so far). If the an application crashes or quit, any pending transaction is rollback (The rollback is actually done the next time the program opens the db). If there is no outstanding transaction open then nothing happens. SQLite is an in-process database so you should not have to worry about closing databases (nobody closes a database when using CoreData on iOS or SQLiteProvider on Android). Similarly any file connection is closed when a program exits
