### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot open file, path

### ISSUE THREAD

**Issue by mealinux** [tekartik/sqflite#580]
Works API 30 but doesn't work level 23 (Android 6.0) -sqlite/sqflite

//settings
```
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  path: ^1.7.0
  sqflite: ^1.3.2+2

```

//my code
```
final String pathDB = "db.sqlite";

  Future<Database> accessDb() async {
    WidgetsFlutterBinding.ensureInitialized();

    String dbPath = join(await getDatabasesPath(), pathDB);

    if (await databaseExists(dbPath)) {
    } else {
      ByteData data = await rootBundle.load('databases/${pathDB}');

      List<int> bytes =
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await Directory(dbPath).create(recursive: true);
      await File(dbPath).writeAsBytes(bytes, flush: true);

    }
    var database = await openDatabase(dbPath, version: 1);
    return database;
  }
```

//pubspec.yaml asset
```
  assets:
    - databases/db.sqlite
```

//error
```
E/flutter ( 5841): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/user/0/com.example.first_app/databases/db.sqlite' (OS Error: Is a directory, errno = 21)
E/flutter ( 5841): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 5841): #1      _rootRunUnary (dart:async/zone.dart:1194:47)
E/flutter ( 5841): #2      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
E/flutter ( 5841): #3      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
E/flutter ( 5841): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)
E/flutter ( 5841): #5      Future._propagateToListeners (dart:async/future_impl.dart:732:32)
E/flutter ( 5841): #6      Future._completeWithValue (dart:async/future_impl.dart:536:5)
E/flutter ( 5841): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)
E/flutter ( 5841): #8      _rootRun (dart:async/zone.dart:1186:13)
E/flutter ( 5841): #9      _CustomZone.run (dart:async/zone.dart:1090:19)
E/flutter ( 5841): #10     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
E/flutter ( 5841): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
E/flutter ( 5841): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5841): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

//flutter docktor -v
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale tr_TR.utf8)
    • Flutter version 1.25.0-8.3.pre at
      /home/alikilic/snap/flutter/common/flutter
    • Framework revision 5d36f2e7f5 (10 gün önce), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alikilic/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (2 available)
    • GT I9500 (mobile)                     • 4d00a3f5beb89029 • android-arm •
      Android 5.0.1 (API 21)
    • Android SDK built for x86 64 (mobile) • emulator-5554    • android-x64 •
      Android 6.0 (API 23) (emulator)

```

//flutter run -d chrome -v
```
[  +80 ms] executing: [/home/alikilic/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] executing: [/home/alikilic/snap/flutter/common/flutter/] git tag
--points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[  +15 ms] Exit code 0 from: git tag --points-at
5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +44 ms] executing: [/home/alikilic/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/alikilic/snap/flutter/common/flutter/] git
ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/home/alikilic/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +92 ms] executing: /home/alikilic/Android/Sdk/platform-tools/adb devices -l
[  +50 ms] List of devices attached
           4d00a3f5beb89029       device usb:1-2 product:ja3gxx model:GT_I9500
           device:ja3g transport_id:5
           emulator-5554          device product:sdk_google_phone_x86_64
           model:Android_SDK_built_for_x86_64 device:generic_x86_64
           transport_id:11
[   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[  +56 ms] No devices found with name or id matching 'chrome'
[  +12 ms] "flutter run" took 254ms.
[  +20 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand
           (package:flutter_tools/src/commands/run.dart:435:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1091:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand
(package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure>
(package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext
(package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[ +262 ms] ensureAnalyticsSent: 255ms
[   +6 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

```

**Comment by alextekartik** [comment]
Well the error speaks for itself (it does not fail in sqflite, it fails before):
```
path = '/data/user/0/com.example.first_app/databases/db.sqlite' (OS Error: Is a directory, errno = 21)
```
And indeed you are creating a folder with this name, so the next File write fails:
```dart
await Directory(dbPath).create(recursive: true);
```
I think what you want is to create the parent directory, so this should fix:
```dart
await Directory(dirname(dbPath)).create(recursive: true);
```

**Comment by mealinux** [comment]
> Well the error speaks for itself (it does not fail in sqflite, it fails before):
> 
> ```
> path = '/data/user/0/com.example.first_app/databases/db.sqlite' (OS Error: Is a directory, errno = 21)
> ```
> 
> And indeed you are creating a folder with this name, so the next File write fails:
> 
> ```dart
> await Directory(dbPath).create(recursive: true);
> ```
> 
> I think what you want is to create the parent directory, so this should fix:
> 
> ```dart
> await Directory(dirname(dbPath)).create(recursive: true);
> ```

many thanks for your answer but still doesn't work without this line `await Directory(dbPath).create(recursive: true);` same error

**Comment by mealinux** [comment]
okay, new app created, copied files and built, works :)
