### ISSUE TITLE
Database is locked exception

### ISSUE THREAD

**Issue by oligazar** [tekartik/sqflite#602]
I'm getting "database is locked" exception. I don't use any transactions in my code though.

```Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=5 "database is locked" UserInfo={NSLocalizedDescription=database is locked}) sql 'BEGIN IMMEDIATE' args []}
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:321:14)
<asynchronous suspension>
#2      SqfliteDatabaseMixin.beginTransaction (package:sqflite_common/src/database_mixin.dart:461:9)
<asynchronous suspension>
#3      SqfliteDatabaseMixin._runTransaction (package:sqflite_common/src/database_mixin.dart:484:13)
<asynchronous suspension>
#4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34:18)
<asynchronous suspension>
#5      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:346:14)
<asynchronous suspension>
#6      DatabaseHelper._insertMap (package:treckerflutter/logic/db/db_helper.dart:1109:5<…>
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=5 "database is locked" UserInfo={NSLocalizedDescription=database is locked}) sql 'DELETE FROM table_position_body' args []}
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnRawUpdate.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:420:22)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34:18)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:346:14)
<asynchronous suspension>
#4      FirebaseHelper.saveLocation (package:treckerflutter/logic/apis/fb_helper.dart:513:7)
<asynchronous suspension>
#5      FirebaseHelper.onLocation (package:treckerflutter/logic/apis/fb_helper.dart:476:9)
<asynchronous suspension>
```
```
flutter: Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction 
flutter: Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
flutter: Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction
```

Methods mentioned in the error trace:
```
Future<int> deleteAllFrom(String table) async {
    Database db = await database;
    return db.rawDelete("DELETE FROM $table");
  }
```
```
Future<void> _insertMap(List<Map<String, dynamic>> items, String tableName,
      {bool shouldClearTable = true}) async {
    Database db = await database;
    final batch = db.batch();
    if (shouldClearTable) {
      print('delete from: $tableName, new items: ${items.length}');
      batch.rawDelete("DELETE FROM $tableName");
    }
    items.forEach((map) {
      map[COL_SAVE_TIME] = DateTime.now().millisecondsSinceEpoch;
      batch.insert(tableName, map,
          conflictAlgorithm: ConflictAlgorithm.replace);
    });
    await batch.commit();
   
    notify(tableName);
  }
```
One thing that may be important here is that 'deleteAllFrom' and '_insertMap' are called from different isolates. Also there wasn't huge insert/updates when the lock happened.

Is there any way to avoid the blocking or resolve the issue in some other way?

**Comment by alextekartik** [comment]
For the time being, sqflite is not cross isolate safe. I don't recommend using it from another isolate as it can bring issues like the one you encounter.

**Comment by oligazar** [comment]
@alextekartik Thanks for the quick reply! Do you happen to know any isolate-safe database implementation as an alternative? Or any other storage solution for that matter? Might having two instances of the db in both isolates be a solution/workaround?

**Comment by alextekartik** [comment]
@oligazar I am not aware of any easy solution, sorry.

**Comment by Mike278** [comment]
@oligazar https://moor.simonbinder.eu/docs/advanced-features/isolates/

**Comment by oligazar** [comment]
> @oligazar https://moor.simonbinder.eu/docs/advanced-features/isolates/

Thanks a lot! Looks very promising!

**Comment by Mike278** [comment]
Just out of curiosity, what are you using isolates for?

The typical reason is that running expensive cpu-bound work on the main UI isolate causes frame drops, so you move that work to a non-UI isolate. It takes longer to communicate over the isolate, so you trade off a bit of overall speed for a smoother UI.

This is pretty much the setup that sqflite already has: the expensive cpu-bound work (using the sqlite api to execute the statement and possibly step through the results) is done in a native thread and communicated over a method channel. This means the only way sqflite should cause frame drops is if you're receiving a very large amount of data over the method channel (where "very large" normally means "more data than should reasonably be displayed on one screen").

Moor, on the other hand, has the option to interact with the sqlite api directly using dart:ffi. In this case, since the expensive cpu-bound work is done directly in Dart, it makes sense to move that work to a separate isolate. 

I haven't benchmarked yet, but I'd be curious to know:
- Is it faster to pass data over a method channel or between isolates?
- Does dart:ffi use the sqlite api faster than native? Might beat JNI on Android, but it's probably hard to beat direct access on iOS

**Comment by JamesMcIntosh** [comment]
The "Warning database has been locked for 0:00:10.000000." is a little bit misleading.

It does not necessarily indicate a database lock, the lock is actually a lock in the `database_mixin.dart` which allow only one statement to execute at a time. If that statement which is currently executing takes a very long time then this message will show. see code snippet below.

One thing what would be nice is to be able to see which query is taking all this time rather than the one which is queued up waiting to start.

@alextekartik Is this what you meant by "_All calls are currently synchronized and transactions block are exclusive._" here:
https://github.com/tekartik/sqflite/blob/master/sqflite/README.md#current-issues

https://github.com/tekartik/sqflite/blob/86ab960e2cc94869ef4418a40865a738dbcc717f/sqflite_common/lib/src/database_mixin.dart#L573
```
// Grab the lock
final operation = _rawLock.synchronized(() {
  if (handleTimeoutWarning) {
    timeoutCompleter.complete();
  }
  return action(txn);
});

// Simply warn the developer as this could likely be a deadlock
if (handleTimeoutWarning) {
  // ignore: unawaited_futures
  timeoutCompleter.future.timeout(
    utils.lockWarningDuration!,
    onTimeout: () {
      utils.lockWarningCallback!(); // Warning database has been locked for 0:00:10.000000.
    },
  );
}
```

**Comment by alextekartik** [comment]
@JamesMcIntosh You're correct that the hint is misleading. That's however a common mistake - use the database object in a transaction - that is sometimes hard to catch. The hint does not help in finding where is the mistake though...

So far I have simply said to simply disable the hint globally using `setLockWarningInfo()` if you indeed have lengthy operations.

> Is this what you meant by "All calls are currently synchronized and transactions block are exclusive."

Correct when using `sqflite` or `sqflite_common_ffi`. When using [`sqflite_common_ffi_async`](https://pub.dev/packages/sqflite_common_ffi_async) that is not true since it uses sqlite_async mechanism. write transaction blocks are exclusive.

A better approach would be to catch the common mistake in a better way. Using Zone in debug mode we could simply catch the incorrect usage of a database object in a transaction block so that it reports a relevant stack trace. I think I'll work on that first and change the hint later, simply stating that locking the database for too long is not a good practice or a potential issue of having too many concurrent access
