### ISSUE TITLE
App crashes upon starting background locator

### ISSUE THREAD

**Issue by izuokoye** [tekartik/sqflite#614]
Good day,
My app keeps crashing anytime I start the background locator -> Stops the background locator -> start the background locator -> crash.

I have this code that registers SQflite plugin

```
if (!registry!!.hasPlugin("com.tekartik.sqflite")) {
            SqflitePlugin.registerWith(registry!!.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
        }
```
I think the crash is caused by SQflite because anytime it crashes I get this error message "Unable to create service rekab.app.background_locator.IsolateHolderService: java.lang.IllegalStateException: Plugin key com.tekartik.sqflite.SqflitePlugin is already in use"

Is there a way to prevent SQflite from running more than once when I try to start the background service?

Below is the error from the terminal:

```
D/BackgroundLocatorPlugin(13239): start locator with Google client
D/AndroidRuntime(13239): Shutting down VM
E/AndroidRuntime(13239): FATAL EXCEPTION: main
E/AndroidRuntime(13239): Process: com.bulwarkpublishing.thermal, PID: 13239
E/AndroidRuntime(13239): java.lang.RuntimeException: Unable to create service rekab.app.background_locator.IsolateHolderService: java.lang.IllegalStateException: Plugin key com.tekartik.sqflite.SqflitePlugin is already in use
E/AndroidRuntime(13239): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
E/AndroidRuntime(13239): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime(13239): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime(13239): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(13239): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(13239): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(13239): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13239): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(13239): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(13239): Caused by: java.lang.IllegalStateException: Plugin key com.tekartik.sqflite.SqflitePlugin is already in use
E/AndroidRuntime(13239): 	at io.flutter.app.FlutterPluginRegistry.registrarFor(FlutterPluginRegistry.java:75)
E/AndroidRuntime(13239): 	at com.bulwarkpublishing.thermal.Application.registerWith(Application.kt:26)
E/AndroidRuntime(13239): 	at rekab.app.background_locator.IsolateHolderExtensionKt.startLocatorService(IsolateHolderExtension.kt:36)
E/AndroidRuntime(13239): 	at rekab.app.background_locator.IsolateHolderService.onCreate(IsolateHolderService.kt:115)
E/AndroidRuntime(13239): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
E/AndroidRuntime(13239): 	... 8 more
I/Process (13239): Sending signal. PID: 13239 SIG: 9
```

**Comment by anoop-ananthan** [comment]
Isn't this a duplicate of https://github.com/rekabhq/background_locator/issues/215?
