### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by zim32** [tekartik/sqflite#651]
Got error Unhandled Exception: Null check operator used on a null value when trying this library.

Platform: Android

versions: 
sqflite 1.3.2+4

My code is:

```
void main() async {
  print(await getDatabasesPath());
}
```

Stacktrace 

```
Installing build/app/outputs/flutter-apk/app.apk...                 4.7s
E/flutter (19225): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (19225): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (19225): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (19225): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (19225): #3      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
E/flutter (19225): #4      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
E/flutter (19225): #5      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:41:35)
E/flutter (19225): #6      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
E/flutter (19225): #7      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
E/flutter (19225): #8      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:41:7)
E/flutter (19225): #9      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:169:26)
E/flutter (19225): #10     getDatabasesPath (package:sqflite/sqflite.dart:161:54)
E/flutter (19225): #11     main (package:app/main.dart:13:15)
E/flutter (19225): #12     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (19225): #13     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (19225): #14     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (19225): #15     _runZoned (dart:async/zone.dart:1789:10)
E/flutter (19225): #16     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (19225): #17     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (19225): #18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (19225): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (19225): 
```

**Comment by zim32** [comment]
Sorry this was my fault. Running flutter without runApp() causes this error inside MethodChannel.binaryMessenge
