### ISSUE TITLE
【windows】open database crash

### ISSUE THREAD

**Issue by baneyue** [tekartik/sqflite#720]
The following error occurs occasionally when opening dB on windows. However, it can be accessed by changing the external SQLite tool of DB

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
The following _CastError was thrown:
type 'Null' is not a subtype of type 'String' in type cast

When the exception was thrown, this was the stack:
#0      SqfliteIsolate.handle (package:sqflite_common_ffi/src/isolate.dart:41:33)
<asynchronous suspension>
#1      FfiMethodCallHandler._isolateHandle (package:sqflite_common_ffi/src/database_factory_ffi.dart:95:12)
<asynchronous suspension>
#2      FfiMethodCallHandler.handleInIsolate (package:sqflite_common_ffi/src/database_factory_ffi.dart:51:20)
<asynchronous suspension>
#3      _SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite_common/src/mixin/factory.dart:20:8)
<asynchronous suspension>
#4      SqfliteDatabaseMixin.openDatabase (package:sqflite_common/src/database_mixin.dart:556:9)
<asynchronous suspension>
#5      SqfliteDatabaseMixin.doOpen (package:sqflite_common/src/database_mixin.dart:649:22)
<asynchronous suspension>
#6      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite_common/src/database.dart:44:7)
<asynchronous suspension>
#7      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:111:18)
<asynchronous suspension>
#8      ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:37:18)
<asynchronous suspension>
#9      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#10     queryAllUser_labelid (package:wxwork_helper/demo/MainViewPage/Tool/MessageQueryDBTool.dart:247:19)
<asynchronous suspension>
═════════════════════════════════════════════════════════════════

![image](https://user-images.githubusercontent.com/1902581/139424001-2eb35fda-e158-41f9-800d-af75ec4ee3f4.png)

**Comment by alextekartik** [comment]
Thanks for the report. I you can manage to show the message where it fails (and the sql statement executed); it would help a a lot in reproducing on my side

**Comment by baneyue** [comment]
only when open database。the database is exists and can open with other sqlite db tools.

![image](https://user-images.githubusercontent.com/1902581/139771339-7c448453-4e45-4b46-ae7c-b75bfb11ce63.png)

**Comment by baneyue** [comment]
@alextekartik Is there any progress on this issue

**Comment by alextekartik** [comment]
I could not manage to reproduce. What could help to try on your side:
* Add some print before to see your path. Build your path (absolute? or relative?) using `join` only and not a mix of join and `\\`:
  ```
  // instead of var path = join(WechatDbPathString + currentUserModel.vid + '\\', 'user.db');
  var path = join(WechatDbPathString + currentUserModel.vid, 'user.db');
  // instead of  join(DatasavePathString + `\\`, id);
  var path = join(DatasavePathString, id);
  // print for debugging
  print('opening $path');
```
* You might try to want `path_provider` for setting the default location of you database.
* Check the database (`PRAGMA integrity_check`) using desktop tools (https://sqliteviewer.com/blog/database-disk-image-malformed)
* Or good if you can share your database so I can try to open it in a unit test.
* You can add extra logs from sqflite itself to see if more info get printed that help analyzing the issue.
* If you can debug the crash, good if you code see the content of the error map in your first picture (error is Map). It seems to be a map without some expected keys), maybe its content will help.
* Try to use `flutter_lints`. You are missing some await (setDatabasesPath) and here the content of the path is important to see (it should be absolute).
* Ah also in your report, good if you can copy the code and paste between triple-ticks instead of pasting images. It is easier to make comment on code.

**Comment by baneyue** [comment]
thanks a lot ,

**Comment by baneyue** [comment]
We have found the cause of this problem because. Wal. SHM and. DB files are out of sync. Our usage scenario will dynamically replace dB. However, the two runtime intermediate files. Wal and. SHM are not replaced synchronously.
