### ISSUE TITLE
Can't delete from table with dismissible widget.

### ISSUE THREAD

**Issue by saurabhdhingra** [tekartik/sqflite#733]
Here's a minimal complete reproducible code sample of what I am trying to do. 
db.dart

```
import 'dart:io';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

class DatabaseHelper {
  static const _dbName = 'myDatabase.db';
  static const _dbVersion = 1;
  static const _table = 'myTable';
  static const colField1 = 'field1';
  static const colField2 = 'field2';

  static final DatabaseHelper instance = DatabaseHelper._init();
  DatabaseHelper._init();

  static Database? _database;
  Future<Database> get database async {
    if (_database != null) return _database!;

    _database = await _initiateDatabase();
    return _database!;
  }

  _initiateDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = join(directory.path, _dbName);
    return await openDatabase(path, version: _dbVersion, onCreate: _onCreate);
  }

  Future _onCreate(Database db, int version) async {
    await db.execute('''CREATE TABLE $_table( 
    $colField1 TEXT,
    $colField2 TEXT)''');
    await db.insert(
      _table,
      {colField1: 'Data1', colField2: 'Data2'},
    );
  }

  Future<List<Map<String, dynamic>>> queryAll() async {
    Database db = await instance.database;
    List<Map<String, dynamic>> item = await db.query(_table);
    return item;
  }

  Future<int> delete(String data) async {
    Database db = await instance.database;
    String dataField2 = 'Data2';
    return await db.delete(_table,
        where: 'colField1 = ? AND colField2 = ?',
        whereArgs: [data, dataField2]);
  }
}

```

home.dart

```
import 'package:flutter/material.dart';
import 'package:github/db.dart';

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late List<Map<String, dynamic>> data;
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    checkData();
  }

  Future checkData() async {
    setState(() {
      isLoading = true;
    });
    List<Map<String, dynamic>> data = await DatabaseHelper.instance.queryAll();
    this.data = data;
    setState(() {
      isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return isLoading
        ? const Center(
            child: CircularProgressIndicator(
              color: Color(0xFF403F3C),
            ),
          )
        : Scaffold(
            appBar: AppBar(),
            body: SafeArea(
              child: ListView.builder(
                itemCount: data.length,
                itemBuilder: (context, i) {
                  final item = data[i];
                  return Center(
                    child: Dismissible(
                      background: Container(
                          color: Colors.red, child: const Icon(Icons.delete)),
                      key: Key(item['field1']),
                      direction: DismissDirection.endToStart,
                      onDismissed: (direction) async {
                        setState(() {
                          data.removeAt(i);
                        });
                        await DatabaseHelper.instance.delete(item['']);
                      },
                      child: ListTile(
                          title: Text(data[i]['field1']),
                          subtitle: Text(data[i]['field2'])),
                    ),
                  );
                },
              ),
            ),
          );
  }
}

```
And here's my flutter run --verbose log

```
[+9103 ms] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: read-only
                    #0      QueryResultSet.length= (package:sqflite_common/src/collection_utils.dart:109:5)
                    #1      ListMixin._closeGap (dart:collection/list.dart:312:10)
                    #2      ListMixin.removeAt (dart:collection/list.dart:539:5)
                    #3      _GithubIssueState.build.<anonymous closure>.<anonymous closure>.<anonymous
closure> (package:github/github.dart:55:32)
                    #4      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
                    #5      _GithubIssueState.build.<anonymous closure>.<anonymous closure>
(package:github/github.dart:54:25)
                    #6      _GithubIssueState.build.<anonymous closure>.<anonymous closure>
(package:github/github.dart:53:36)
                    #7      _DismissibleState._handleResizeProgressChanged
(package:flutter/src/widgets/dismissible.dart:547:27)
                    #8      AnimationLocalListenersMixin.notifyListeners
(package:flutter/src/animation/listener_helpers.dart:155:19)
                    #9      AnimationController._tick (package:flutter/src/animation/animation_<…>
```

**Comment by alextekartik** [comment]
Ok I see, as the stack show, it crashes here:

```dart
 setState(() {
  data.removeAt(i);
});
```

The resulting list from sqflite is not a normal list that you can modify so its write operation will throw a read-only (not well documented) error.

```dart
List<Map<String, dynamic>> data = await DatabaseHelper.instance.queryAll();
// Solution here: clone the list
this.data = List.from(data);
```

### The doc I'm adding

`query` is for reading a table content. It returns a list of map.

The list is read-only. If you want to modify the results by adding/deleting items in memory,
you need to clone the list:

```dart
// This throws an error
list.add(<String, Object?>{'name': 'some data'});
```
```dart
// This works
list = List.from(list)
list.add(<String, Object?>{'name': 'some data'});
```

Each item (map) of the list is read-only too so you need to clone it if you want to modify the result.
```dart
map = list.first;
// This crashes
map['name'] = 'other';
```
```dart
// This works
map = Map.from(map);
map['name'] = 'other';
```
