### ISSUE TITLE
os_unix.c:33495: (24) openDirectory

### ISSUE THREAD

**Issue by tiholic** [tekartik/sqflite#80]
## Steps to Reproduce

I never used to get this issue in initial stages of development. But get this error often these days ( most probably heavy data operations ).
It will vanish if I re-run the app. Hot reload, hot restart will keep repeating the error (```
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646```).

## Logs
```
I/flutter (30919): Sync complete
E/SQLiteLog(30919): (14) cannot open file at line 33495 of [605907e73a]
E/SQLiteLog(30919): (14) os_unix.c:33495: (24) openDirectory(/data/user/0/com.infitio.gromorshakti/app_flutter) - 
E/Surface (30919): queueBuffer: error queuing buffer to SurfaceTexture, -22
I/Adreno  (30919): QueueBuffer: queueBuffer failed
E/Surface (30919): queueBuffer: error queuing buffer to SurfaceTexture, -22
I/Adreno  (30919): QueueBuffer: queueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/SQLiteLog(30919): (14) cannot open file at line 33495 of [605907e73a]
E/SQLiteLog(30919): (14) os_unix.c:33495: (24) openDirectory(/data/user/0/com.infitio.gromorshakti/app_flutter) - 
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/SQLiteLog(30919): (14) cannot open file at line 33495 of [605907e73a]
E/SQLiteLog(30919): (14) os_unix.c:33495: (24) openDirectory(/data/user/0/com.infitio.gromorshakti/app_flutter) - 
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/CursorWindow(30919): Could not allocate CursorWindow '/data/user/0/com.infitio.gromorshakti/app_flutter/app_dev_r72.db' of size 2097152 due to error -24.
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/flutter (30919): error placing order
I/flutter (30919): DatabaseException(Cursor window allocation of 2048 kb failed. ) sql 'PRAGMA user_version;' args []}
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/BpSurfaceComposerClient(30919): Failed to transact (-1)
E/BpSurfaceComposerClient(30919): Failed to transact (-1)
I/FlutterActivityDelegate(30919): onResume setting current activity to this
D/PhoneWindow(30919): setNavigationBarColor color: ff000000
W/GraphicBufferMapper(30919): importBuffer(0x77e50bbc00) failed: 5
E/GraphicBuffer(30919): unflatten: registerBuffer failed: Unknown error -5 (5)
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: 5
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Parcel  (30919): fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Parcel  (30919): fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(30919): swapBuffers encountered EGL error 12301 on 0x77f9a71b80, halting rendering...
W/GraphicBufferMapper(30919): importBuffer(0x77cf70c300) failed: 5
E/GraphicBuffer(30919): unflatten: registerBuffer failed: Unknown error -5 (5)
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: 5
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Parcel  (30919): fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Parcel  (30919): fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): queueBuffer: error queuing buffer to SurfaceTexture, -22
I/Adreno  (30919): QueueBuffer: queueBuffer failed
E/Parcel  (30919): fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 2, error: Too many open files
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/SQLiteLog(30919): (14) cannot open file at line 33495 of [605907e73a]
E/SQLiteLog(30919): (14) os_unix.c:33495: (24) openDirectory(/data/user/0/com.infitio.gromorshakti/app_flutter) - 
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/CursorWindow(30919): Could not allocate CursorWindow '/data/user/0/com.infitio.gromorshakti/app_flutter/app_dev_r72.db' of size 2097152 due to error -24.
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/flutter (30919): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30919): DatabaseException(Cursor window allocation of 2048 kb failed. ) sql 'PRAGMA user_version;' args []}
E/flutter (30919): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #1      SqfliteDatabase.txnRawQuery.<anonymous closure> (package:sqflite/src/database.dart:324:14)
E/flutter (30919): #2      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:259:26)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #3      SqfliteDatabase.txnRawQuery (package:sqflite/src/database.dart:323:12)
E/flutter (30919): #4      SqfliteDatabaseExecutor.rawQuery (package:sqflite/src/database.dart:93:10)
E/flutter (30919): #5      SqfliteDatabase.getVersion (package:sqflite/src/database.dart:435:45)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #6      SqfliteDatabase.doOpen.<anonymous closure> (package:sqflite/src/database.dart:559:34)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #7      SqfliteDatabase._runTransaction (package:sqflite/src/database.dart:411:28)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #8      SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:426:14)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #9      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:259:26)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #10     SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:290:7)
E/flutter (30919): #11     SqfliteDatabase.transaction (package:sqflite/src/database.dart:425:12)
E/flutter (30919): #12     SqfliteDatabase.doOpen (package:sqflite/src/database.dart:554:15)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #13     SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:166:26)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #14     Lock._runTask (package:synchronized/src/synchronized_impl.dart:147:27)
E/flutter (30919): #15     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62:14)
E/flutter (30919): #16     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72:17)
E/flutter (30919): #17     Lock.synchronized (package:synchronized/src/synchronized_impl.dart:140:12)
E/flutter (30919): #18     SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:163:25)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #19     SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:114:39)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #20     openDatabase (package:sqflite/sqflite.dart:317:31)
E/flutter (30919): #21     StorageProvider.open (package:adhara/datainterface/storage/storage_provider.dart:68:17)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #22     StorageProvider.db (package:adhara/datainterface/storage/storage_provider.dart:92:11)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #23     StorageProvider.getRawList (package:adhara/datainterface/storage/storage_provider.dart:147:30)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #24     StorageProvider.getRaw (package:adhara/datainterface/storage/storage_provider.dart:201:33)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #25     StorageProvider.get (package:adhara/datainterface/storage/storage_provider.dart:209:21)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #26     KeyValueStorageProvider.getData (package:adhara/datainterface/storage/key_value_storage_provider.dart:42:21)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #27     AppDataInterface.getTopProducts (package:gromor_shakti/datainterface/AppDataInterface.dart:224:55)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #28     _HomePageState.fetchData (package:gromor_shakti/screens/HomePage.dart:43:41)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #29     AdharaState._callFetchData (package:adhara/widgets/stateful_widget.dart:35:5)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #30     AdharaState._callFirstLoad (package:adhara/widgets/stateful_widget.dart:26:7)
E/flutter (30919): <asynchronous suspension>
E/flutter (30919): #31     AdharaState.initState (package:adhara/widgets/stateful_widget.dart:18:5)
E/flutter (30919): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter (30919): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (30919): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30919): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30919): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30919): #37     Element.inflateWidget (package:flutter/src/widgets/fr
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed
E/Surface (30919): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
I/Adreno  (30919): DequeueBuffer: dequeueBuffer failed

```

## Flutter Analyze
```
Analyzing gs_app...
No issues found! (ran in 16.7s)
```

##doctor -v
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-IN)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Rohit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\Rohit\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • ONEPLUS A5010 • 192.168.1.2:5556 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by alextekartik** [comment]
Thanks for the report. Indeed that's not good. I will check again whether we could still have open cursors (Cursor window allocation of 2048 kb failed) that could cause such issue. Can I get an idea of the size of your database (KB) and queries (item count and item size)

**Comment by tiholic** [comment]
452KB at the minimal. And it keeps growing by 4KB for every order placement (It's an e-Commerce portal).

Queries:
Get list - Maximum no's 50 at a time tested till now and each entry returned by the query will roughly be around a KB

**Comment by alextekartik** [comment]
As said in another bug, maybe you can try to open the database only once and keep a global reference to it

**Comment by tiholic** [comment]
Thanks :D that worked
