### ISSUE TITLE
E/SQLiteLog( 3977): (5) database is locked

### ISSUE THREAD

**Issue by tiholic** [tekartik/sqflite#82]
I am opening and closing the DB connection on each query. Not sure if this is the proper way. I am facing problems when asynchronous user interaction happens. For each page I will make at least one query.

When the db is being queried for current page, say the user navigates to another page.
Another connection will try to open which is throwing DB locked exception.

I'm confused between "Always keeping the connection open" and "Open and close as required"?
If I keep it open always when do I close it?

Please suggest if there is any proper way to handle query heavy applications. 

#### Log
```
E/SQLiteLog( 3977): (5) database is locked
E/SQLiteDatabase( 3977): Failed to open database '/data/user/0/com.infitio.gromorshakti/app_flutter/app_dev_r72.db'.
E/SQLiteDatabase( 3977): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:902)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:647)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:333)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:305)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:204)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:879)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:765)
E/SQLiteDatabase( 3977): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:782)
E/SQLiteDatabase( 3977): 	at com.tekartik.sqflite.SqflitePlugin$Database.open(SqflitePlugin.java:764)
E/SQLiteDatabase( 3977): 	at com.tekartik.sqflite.SqflitePlugin$Database.access$900(SqflitePlugin.java:755)
E/SQLiteDatabase( 3977): 	at com.tekartik.sqflite.SqflitePlugin.onOpenDatabaseCall(SqflitePlugin.java:641)
E/SQLiteDatabase( 3977): 	at com.tekartik.sqflite.SqflitePlugin.onMethodCall(SqflitePlugin.java:738)
E/SQLiteDatabase( 3977): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/SQLiteDatabase( 3977): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/SQLiteDatabase( 3977): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/SQLiteDatabase( 3977): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/SQLiteDatabase( 3977): 	at android.os.Looper.loop(Looper.java:142)
E/SQLiteDatabase( 3977): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
E/SQLiteDatabase( 3977): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteDatabase( 3977): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
E/SQLiteDatabase( 3977): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/Choreographer( 3977): Skipped 150 frames!  The application may be doing too much work on its main thread.
E/flutter ( 3977): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3977): DatabaseException(database is locked (code 5): , while compiling: PRAGMA journal_mode)
E/flutter ( 3977): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #1      SqfliteDatabase._openDatabase (package:sqflite/src/database.dart:465:12)
E/flutter ( 3977): #2      SqfliteDatabase.doOpen (package:sqflite/src/database.dart:498:28)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #3      SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:166:26)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #4      Lock._runTask (package:synchronized/src/synchronized_impl.dart:147:27)
E/flutter ( 3977): #5      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62:14)
E/flutter ( 3977): #6      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72:17)
E/flutter ( 3977): #7      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:140:12)
E/flutter ( 3977): #8      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:163:25)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #9      SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:114:39)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #10     openDatabase (package:sqflite/sqflite.dart:317:31)
E/flutter ( 3977): #11     StorageProvider.open (package:adhara/datainterface/storage/storage_provider.dart:68:17)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #12     StorageProvider.db (package:adhara/datainterface/storage/storage_provider.dart:92:11)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #13     StorageProvider.getRawList (package:adhara/datainterface/storage/storage_provider.dart:147:30)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #14     DataInterface.query (package:adhara/datainterface/data_interface.dart:120:28)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #15     AppDataInterface.getCartItems (package:gromor_shakti/datainterface/AppDataInterface.dart:342:40)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #16     _CartPageState.fetchData (package:gromor_shakti/screens/store/Cart.dart:33:37)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #17     _CartPageState.initState (package:gromor_shakti/screens/store/Cart.dart:27:5)
E/flutter ( 3977): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter ( 3977): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 3977): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 3977): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 3977): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 3977): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter ( 3977): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 3977): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 3977): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 3977): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 3977): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3977): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3977): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 3977): #41     Element.rebuild (package:flutter/src/
E/flutter ( 3977): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3977): DatabaseException(database is locked (code 5))
E/flutter ( 3977): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #1      SqfliteDatabase.invokeExecute (package:sqflite/src/database.dart:300:12)
E/flutter ( 3977): #2      SqfliteDatabase.txnExecute.<anonymous closure> (package:sqflite/src/database.dart:295:14)
E/flutter ( 3977): #3      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:259:26)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #4      SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:290:7)
E/flutter ( 3977): #5      SqfliteDatabase.txnExecute (package:sqflite/src/database.dart:294:12)
E/flutter ( 3977): #6      SqfliteDatabase.beginTransaction (package:sqflite/src/database.dart:383:15)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #7      SqfliteDatabase._runTransaction (package:sqflite/src/database.dart:407:19)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #8      SqfliteDatabase.transaction.<anonymous closure> (package:sqflite/src/database.dart:426:14)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #9      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:259:26)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #10     SqfliteDatabase.txnWriteSynchronized (package:sqflite/src/database.dart:290:7)
E/flutter ( 3977): #11     SqfliteDatabase.transaction (package:sqflite/src/database.dart:425:12)
E/flutter ( 3977): #12     SqfliteDatabase.doOpen (package:sqflite/src/database.dart:554:15)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #13     SqfliteDatabaseOpenHelper.openDatabase.<anonymous closure> (package:sqflite/src/database.dart:166:26)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #14     Lock._runTask (package:synchronized/src/synchronized_impl.dart:147:27)
E/flutter ( 3977): #15     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62:14)
E/flutter ( 3977): #16     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72:17)
E/flutter ( 3977): #17     Lock.synchronized (package:synchronized/src/synchronized_impl.dart:140:12)
E/flutter ( 3977): #18     SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:163:25)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #19     SqfliteDatabaseFactory.openDatabase (package:sqflite/src/database_factory.dart:114:39)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #20     openDatabase (package:sqflite/sqflite.dart:317:31)
E/flutter ( 3977): #21     StorageProvider.open (package:adhara/datainterface/storage/storage_provider.dart:68:17)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #22     StorageProvider.db (package:adhara/datainterface/storage/storage_provider.dart:92:11)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #23     StorageProvider.getRawList (package:adhara/datainterface/storage/storage_provider.dart:147:30)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #24     StorageProvider.getByIdRaw (package:adhara/datainterface/storage/storage_provider.dart:217:33)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #25     DataInterface.queryOne (package:adhara/datainterface/data_interface.dart:85:28)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #26     AppDataInterface.getFarmer (package:gromor_shakti/datainterface/AppDataInterface.dart:469:33)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #27     AppDataInterface.fillOrder (package:gromor_shakti/datainterface/AppDataInterface.dart:360:27)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #28     AppDataInterface.getOrders (package:gromor_shakti/datainterface/AppDataInterface.dart:398:24)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #29     AppDataInterface.getTopProducts (package:gromor_shakti/datainterface/AppDataInterface.dart:232:32)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #30     _HomePageState.fetchData (package:gromor_shakti/screens/HomePage.dart:43:41)
E/flutter ( 3977): <asynchronous suspension>
E/flutter ( 3977): #31     _HomePageState._buildTopProducts.<anonymous closure>.<anonymous closure> (package:gromor_shakti/screens/HomePage.dart:211:49)
E/flutter ( 3977): #32     _ProductCardState.routeToProductDetails.<anonymous closure> (package:gromor_shakti/widgets/ProductCard.dart:80:18)
E/flutter ( 3977): #33     _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter ( 3977): #34     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter ( 3977): #35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter ( 3977): #36     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter ( 3977): #37     Future._completeWithValue (dart:async/future_impl.dart:477:5)
E/flutter ( 3977): #38     Future._async
```

**Comment by alextekartik** [comment]
I have my personnal usage recommendation here:
https://github.com/tekartik/sqflite/blob/master/doc/usage_recommendations.md

But of course, it might depends on the usage and I have not tested very heavy situations. I would say just see what happens if you don't close it (it will get closed when the app quits) and if it works keep it this way

**Comment by tiholic** [comment]
Thanks @alextekartik 

Can you please explain whats the difference between using `singleInstance:true` in `openDatabase` and having a global reference?

**Comment by tiholic** [comment]
@alextekartik I've tested it the whole week, It is working like a charm with single instance. Thanks :D

**Comment by tiholic** [comment]
:

**Comment by wkable** [comment]
Your suggestion to this problem is using a single instance, but database is usually closed immediately after usage, which will otherwise cause memory leak. Do you mean not to close the database and keep the single instance across the lifetime of the app? Moreover, your document says that by default the database for the same path will return a single instance, meaning that the call to 'openDatabase' has been a single instance call and it's not necessary to do single instance call by the user, isn't it?
Moreover, the document says we can do 'perform database initialization such as enabling foreign keys or write-ahead logging' in `onConfigure` callback, but how shall we enable write-ahead logging when there is no API for this?
