### ISSUE TITLE
No such table error 

### ISSUE THREAD

**Issue by beproductivedevelop34** [tekartik/sqflite#829]
```
E/Dart    ( 4638): Invalid UTF8 sequence encountered, 
E/Dart    ( 4638): (Error Code: FD + idx: 234 )
E/Dart    ( 4638): (Error Code: 64 + idx: 235 )
E/Dart    ( 4638): (Error Code: 22 + idx: 236 )
E/Dart    ( 4638): (Error Code: 20 + idx: 237 )
E/Dart    ( 4638): (Error Code: 3A + idx: 238 )
E/Dart    ( 4638): (Error Code: 20 + idx: 239 )
E/Dart    ( 4638): (Error Code: 69 + idx: 240 )
E/Dart    ( 4638): (Error Code: 64 + idx: 241 )
E/Dart    ( 4638): (Error Code: 2C + idx: 242 )
E/Dart    ( 4638): (Error Code: D + idx: 243 )
E/Dart    ( 4638): 
E/Dart    ( 4638): Invalid UTF8 sequence encountered, 
E/Dart    ( 4638): (Error Code: FD + idx: 234 )
E/Dart    ( 4638): (Error Code: 64 + idx: 235 )
E/Dart    ( 4638): (Error Code: 22 + idx: 236 )
E/Dart    ( 4638): (Error Code: 20 + idx: 237 )
E/Dart    ( 4638): (Error Code: 3A + idx: 238 )
E/Dart    ( 4638): (Error Code: 20 + idx: 239 )
E/Dart    ( 4638): (Error Code: 69 + idx: 240 )
E/Dart    ( 4638): (Error Code: 64 + idx: 241 )
E/Dart    ( 4638): (Error Code: 2C + idx: 242 )
E/Dart    ( 4638): (Error Code: D + idx: 243 )
E/Dart    ( 4638): 
```
```
E/SQLiteLog( 4638): (1) no such table: Persons
E/flutter ( 4638): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: DatabaseException(no such table: Persons (code 1): , while compiling: SELECT * FROM Persons) sql 'SELECT * FROM Persons' args []
E/flutter ( 4638): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): #1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:404:30)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:344:14)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): #4      KisilerO.readData (package:database/KisilerO.dart:15:37)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): #5      _MyHomePageState.writedData (package:database/main.dart:37:26)
E/flutter ( 4638): <asynchronous suspension>
E/flutter ( 4638): 
```

**Comment by FDhunterz** [comment]
maybe you can try https://pub.dev/packages/sql_query
