### ISSUE TITLE
[Windows]cannot start a transaction within a transaction   Causing statement: BEGIN IMMEDIATE

### ISSUE THREAD

**Issue by ccchp** [tekartik/sqflite#847]
Hello,I have a problem on windows, but i can't find the reason,the error log is:

```SqfliteFfiException(sqlite_error: 1, , SqliteException(1): cannot start a transaction within a transaction
  Causing statement: BEGIN IMMEDIATE}) DatabaseException(SqliteException(1): cannot start a transaction within a transaction
  Causing statement: BEGIN IMMEDIATE) sql 'BEGIN IMMEDIATE' {details: {database: {path: C:\Users\xxx\AppData\Roaming\xxx\db\xxx.db, id: 1, readOnly: false, singleInstance: true}}}, stackTrace: #0      SqfliteIsolate.handle (package:sqflite_common_ffi/src/isolate.dart:41)
<asynchronous suspension>
#1      FfiMethodCallHandler._isolateHandle (package:sqflite_common_ffi/src/database_factory_ffi.dart:96)
<asynchronous suspension>
#2      FfiMethodCallHandler.handleInIsolate (package:sqflite_common_ffi/src/database_factory_ffi.dart:52)
<asynchronous suspension>
#3      _SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite_common/src/mixin/factory.dart:22)
<asynchronous suspension>
#4      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:319)
<asynchronous suspension>
#5      SqfliteDatabaseMixin.beginTransaction (package:sqflite_common/src/database_mixin.dart:459)
<asynchronous suspension>
#6      SqfliteDatabaseMixin._runTransaction (package:sqflite_common/src/database_mixin.dart:482)
<asynchronous suspension>
#7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#8      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:344)
<asynchronous suspension>```

I need some help, thx

**Comment by alextekartik** [comment]
Some code of what you are doing would help! SQLite does not support nested transaction so you are not supposed to call `BEGIN TRANSACTION` but should use `db.transaction`
