### ISSUE TITLE
database corruption at line...

### ISSUE THREAD

**Issue by astheras** [tekartik/sqflite#864]
greetings, 

i have a problem when i try to open db.  

`
I/flutter (18113): 1 /data/user/0/com.astheras.lww/databases/Моя корпорація.db
E/SQLiteLog(18113): (1) near "(": syntax error
E/SQLiteLog(18113): (11) database corruption at line 119897 of [68b898381a]
E/SQLiteLog(18113): (1) near "(": syntax error
E/SQLiteLog(18113): (11) database corruption at line 119897 of [68b898381a]
E/SQLiteLog(18113): (11) malformed database schema (gen_creature_list) - near "(": syntax error
E/DefaultDatabaseErrorHandler(18113): Corruption reported by sqlite on database: /data/user/0/com.astheras.lww/databases/Моя корпорація.db
E/SQLiteDatabase(18113): DB wipe detected: package=com.astheras.lww reason=corruption file=/data/user/0/com.astheras.lww/databases/Моя корпорація.db ctime=2022-09-10T17:29:35Z mtime=2022-09-10T17:29:35Z atime=2022-09-10T17:28:40Z checkfile [unable to obtain timestamp]
E/SQLiteDatabase(18113): java.lang.Throwable: STACKTRACE
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteDatabase.wipeDetected(SQLiteDatabase.java:2883)
E/SQLiteDatabase(18113): 	at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:60)
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:420)
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteProgram.onCorruption(SQLiteProgram.java:119)
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:67)
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
E/SQLiteDatabase(18113): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
E/SQLiteDatabase(18113): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
E/SQLiteDatabase(18113): 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
E/SQLiteDatabase(18113): 	at com.tekartik.sqflite.SqflitePlugin.query(SqflitePlugin.java:493)
E/SQLiteDatabase(18113): 	at com.tekartik.sqflite.SqflitePlugin.access$000(SqflitePlugin.java:70)
E/SQLiteDatabase(18113): 	at com.tekartik.sqflite.SqflitePlugin$1.run(SqflitePlugin.java:314)
E/SQLiteDatabase(18113): 	at android.os.Handler.handleCallback(Handler.java:900)
E/SQLiteDatabase(18113): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/SQLiteDatabase(18113): 	at android.os.Looper.loop(Looper.java:219)
E/SQLiteDatabase(18113): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/DefaultDatabaseErrorHandler(18113): rename failed: /data/user/0/com.astheras.lww/databases/Моя корпорація.db-wal to /data/user/0/com.astheras.lww/databases/Моя корпорація.db-walcorrupted
W/SQLiteLog(18113): (28) file renamed while open: /data/user/0/com.astheras.lww/databases/Моя корпорація.db
E/DefaultDatabaseErrorHandler(18113): deleting the database file: /data/user/0/com.astheras.lww/databases/Моя корпорація.db
W/HwDatabaseErrorReporter(18113): reportCorruption is triggered.
D/iMonitor(18113): create: 942010005
I/iMonitor(18113): send: 942010005
`

when i execute gen_creature_list   (mentioned view in the error message) in sqlite studio, i get the result without any error. After this message db recreates with default tables. can somebody help me?

**Comment by astheras** [comment]
The issue has been resolved.   it's all because of row_number in the view((
