### ISSUE TITLE
Some raw query fails on older android versions while DB helper works

### ISSUE THREAD

**Issue by chaudharydeepanshu** [tekartik/sqflite#870]
# Issue
A raw query with `ON CONFLICT` like the below fails on Android 9 while works completely fine in Android 12

```sql
rawInsert('''
INSERT INTO ReadCountUserDetails (UserID, ReadCount, TopicID)
SELECT '$userID',
       $newReadCount,
       '$topicID'
FROM Topics
WHERE EXISTS
    (SELECT 1
     FROM Topics
     WHERE TopicID = '$topicID')
  AND EXISTS
    (SELECT 1
     FROM Users
     WHERE UserID = '$userID')
LIMIT 1 ON CONFLICT(UserID, TopicID) DO
UPDATE
SET ReadCount = $newReadCount
''')
```

But writing the above query with DB helper worked fine on all android versions

```dart
insert(
        "ReadCountUserDetails",
        {
          'UserID': userID,
          'ReadCount': newReadCount,
          'TopicID': topicID
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
)
```

# Error
The error I and my testers received on android 9 wth rawQuery is this:
```
E/SQLiteLog( 9788): (1) near "ON": syntax error
E/flutter ( 9788): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR): , while compiling: INSERT INTO ReadCountUserDetails (UserID, ReadCount, TopicID)
E/flutter ( 9788):         SELECT '3PIZjKprlLeCP1ZOItZkqKbMGXv2',
E/flutter ( 9788):         1,
E/flutter ( 9788):         'e991cd2e-a6d5-4214-9a33-3bdacf1de02f'
E/flutter ( 9788):         FROM Topics
E/flutter ( 9788):         WHERE EXISTS
E/flutter ( 9788):         (SELECT 1
E/flutter ( 9788):         FROM Topics
E/flutter ( 9788):         WHERE TopicID = 'e991cd2e-a6d5-4214-9a33-3bdacf1de02f')
E/flutter ( 9788):     AND EXISTS
E/flutter ( 9788):     (SELECT 1
E/flutter ( 9788):         FROM Users
E/flutter ( 9788):         WHERE UserID = '3PIZjKprlLeCP1ZOItZkqKbMGXv2')
E/flutter ( 9788):     LIMIT 1 ON CONFLICT(UserID, TopicID) DO
E/flutter ( 9788):     UPDATE
E/flutter ( 9788):     SET ReadCount = 1) sql 'INSERT INTO ReadCountUserDetails (UserID, ReadCount, TopicID)
E/flutter ( 9788):         SELECT '3PIZjKprlLeCP1ZOItZkqKbMGXv2',
E/flutter ( 9788):         1,
E/flutter ( 9788):         'e991cd2e-a6d5-4214-9a33-3bdacf1de02f'
E/flutter ( 9788):         FROM Topics
E/flutter ( 9788):         WHERE EXISTS
E/flutter ( 9788):         (SELECT 1
E/flutter ( 9788):         FROM Topics
E/flutter ( 9788):         WHERE TopicID = 'e991cd2e-a6d5-4214-9a33-3bdacf1de02f')
E/flutter ( 9788):     AND EXISTS
E/flutter ( 9788):     (SELECT 1
E/flutter ( 9788):         FROM Users
E/flutter ( 9788):         WHERE UserID = '3PIZjKprlLeCP1ZOItZkqKbMGXv2')
E/flutter ( 9788):     LIMIT 1 ON CONFLICT(UserID, TopicID) DO
E/flutter ( 9788):     UPDATE
E/flutter ( 9788):     SET ReadCount = 1' args []
E/flutter ( 9788): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #1      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:392:14)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:344:14)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #4      DbManager.increaseATopicReadCount (package:course_app/databases/sqlite/db_manager.dart:606:12)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #5      TopicDetailsState.increaseReadCount (package:course_app/state/topic_details_provider.dart:602:5)
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): 
```

# What I found
I have noticed that all my rawQuery with `ON CONFLICT` in them fails on Android version 9 but works just fine in Android 12.

# To reproduce
1. write a rawQuery with `ON CONFLICT`.
2. Run it on Android 9 emulator or physical device

Also, if this is something intentional in older androids with using rawQuery then I think it should be mentioned specifically in the pub.dev readme as it could have drastic effects when completing parts of the project in rawQuery and finding out this later on.

If you need any more information regarding this issue then please let me know.

Thank you.

**Comment by chaudharydeepanshu** [comment]
Thanks a lot for explaining and also providing solutions to the issue. I will look into the solutions you provided to see which will work best in our case. 

Thanks again for the quick response 👍.
