### ISSUE TITLE
[Web] Failure To Install Binaries

### ISSUE THREAD

**Issue by mterenzi** [tekartik/sqflite#957]
Following the installation documentation on https://pub.dev/packages/sqflite_common_ffi_web, I tried to run the following command:

```
dart run sqflite_common_ffi_web:setup
```

However I keep getting this error:
```
Could not find a file named "pubspec.yaml" in "/Users/_/.pub-cache/hosted/pub.dartlang.org/_flutterfire_internals-1.0.18".
#0      new Pubspec.load (package:pub/src/pubspec.dart:306:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:121:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:116:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:339:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:302:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

I have depended on both:
```sqflite_common_ffi_web: '>=0.1.0-dev.1'```
and
```sqflite_common_ffi_web: ^0.3.3+1```

Running on MacOS

Any suggestions to fix this? I have also tried installing the `_flutterfire_internals` package.

Thank you and please let me know if more information is required.

**Comment by mterenzi** [comment]
Flutter Doctor Info
```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/Shared/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPad (9th generation) (mobile) • 47D12C19-70AE-463B-B7B3-777A603429DC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by alextekartik** [comment]
That is weird indeed. I don't have much idea. I'll be interested to know if it works if you use the command globally (dart run global instead of dart run):

```console
# Activate package globally
flutter pub global activate sqflite_common_ffi_web
# Build and copy the binaries
flutter pub global run sqflite_common_ffi_web:setup --force
```

You can also try to delete the folder `/Users/_/.pub-cache/hosted/pub.dartlang.org/_flutterfire_internals-1.0.18` and perform `flutter pub get` again to have it resinstalled properly. You can also try to repair the cache (see dart docs).

**Comment by mterenzi** [comment]
Deleting the package cache files didnt help, but activating the package globally and running it that way worked.
Thank you
