### ISSUE TITLE
Table in SQFlite

### ISSUE THREAD

**Issue by techSavvy41** [tekartik/sqflite#97]
```
E/SQLiteLog( 3786): (1) no such table: tb_ibadah
E/flutter ( 3786): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 3786): DatabaseException(no such table: tb_ibadah (code 1): , while compiling: SELECT * FROM tb_ibadah) sql 'SELECT * FROM tb_ibadah' args []}
E/flutter ( 3786): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 3786): <asynchronous suspension>
E/flutter ( 3786): #1      SqfliteDatabase.txnRawQuery.<anonymous closure> (package:sqflite/src/database.dart:329:14)
E/flutter ( 3786): #2      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:278:22)
E/flutter ( 3786): #3      Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter ( 3786): #4      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter ( 3786): #5      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter ( 3786): #6      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter ( 3786): #7      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:274:37)
E/flutter ( 3786): <asynchronous suspension>
E/flutter ( 3786): #8      SqfliteDatabase.txnRawQuery (package:sqflite/src/database.dart:328:12)
E/flutter ( 3786): #9      SqfliteDatabaseExecutor.rawQuery (package:sqflite/src/database.dart:93:10)
E/flutter ( 3786): #10     _MyHalamanManasikState._ambilData (file:///D:/JERBEE/flutter_manasik/lib/hal_manasik.dart:30:39)
E/flutter ( 3786): <asynchronous suspension>
E/flutter ( 3786): #11     _MyHalamanManasikState.initState (file:///D:/JERBEE/flutter_manasik/lib/hal_manasik.dart:22:5)
E/flutter ( 3786): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 3786): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 3786): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 3786): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 3786): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
E/flutter ( 3786): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 3786): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 3786): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 3786): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter ( 3786): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 3786): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 3786): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 3786): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 3786): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 3786): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter ( 3786): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 3786): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 3786): #29     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
E/flutter ( 3786): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 3786): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 3786): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter ( 3786): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter ( 3786): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
E/flutter ( 3786): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
E/flutter ( 3786): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 3786): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 3786): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 3786): #39     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
E/flutter ( 3786): #40     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:20)
E/flutter ( 3786): #41     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 3786): #42     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
E/flutter ( 3786): #43     RenderSl                                                                                                   
```

i just load the database and i want to SELECT my table, and it say "no such table" although in database the table is exist ..

i copy the database file from my friend pc, and in my friend pc it works fine. but when i try in my laptop, it doesn't work and say "no such table"

here is the function to load db and select

   ```
 io.Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, "manasikdb.sqlite");

    Database database = await openDatabase(path, version: 1);
      List<Map> data = await database.rawQuery('SELECT * FROM tb_ibadah');
      setState(() {
         print(data);
      });
```

**Comment by alextekartik** [comment]
Not sure where you copy the database (the database has to be on the device not on your PC). Maybe check if the file exists at `path` first and for example list existing tables: https://github.com/tekartik/sqflite/blob/master/doc/dev_tips.md#list-existing-tables
